# Generated by Django 5.2.1 on 2025-10-11 13:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveBlockedDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField(verbose_name="From Date")),
                ("to_date", models.DateField(verbose_name="To Date")),
                ("reason", models.CharField(max_length=200, verbose_name="Reason")),
                (
                    "applies_to_company",
                    models.BooleanField(
                        default=True, verbose_name="Applies to Company"
                    ),
                ),
                (
                    "block_days",
                    models.PositiveIntegerField(default=0, verbose_name="Block Days"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Leave Blocked Date",
                "verbose_name_plural": "Leave Blocked Dates",
                "ordering": ["from_date"],
            },
        ),
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Policy Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "min_employment_months",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Minimum Employment (Months)"
                    ),
                ),
                (
                    "applicable_to_probation",
                    models.BooleanField(
                        default=False, verbose_name="Applicable to Probation"
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(default=True, verbose_name="Requires Approval"),
                ),
                (
                    "auto_approve_half_day",
                    models.BooleanField(
                        default=False, verbose_name="Auto Approve Half Day"
                    ),
                ),
                (
                    "max_days_auto_approve",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Max Days Auto Approve"
                    ),
                ),
                (
                    "include_regional_holidays",
                    models.BooleanField(
                        default=True, verbose_name="Include Regional Holidays"
                    ),
                ),
                (
                    "regional_holiday_list",
                    models.TextField(
                        blank=True,
                        help_text="JSON format holiday configuration",
                        verbose_name="Regional Holiday List",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Leave Policy",
                "verbose_name_plural": "Leave Policies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Leave Type")),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                (
                    "max_days_per_year",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Max Days Per Year"
                    ),
                ),
                (
                    "carry_forward_allowed",
                    models.BooleanField(
                        default=False, verbose_name="Carry Forward Allowed"
                    ),
                ),
                (
                    "max_carry_forward_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Max Carry Forward Days"
                    ),
                ),
                (
                    "encashment_allowed",
                    models.BooleanField(
                        default=False, verbose_name="Encashment Allowed"
                    ),
                ),
                (
                    "include_holiday",
                    models.BooleanField(default=False, verbose_name="Include Holidays"),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=True, verbose_name="Paid Leave"),
                ),
                (
                    "apply_in_advance_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Apply in Advance (Days)"
                    ),
                ),
                (
                    "maximum_continuous_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="Max Continuous Days"
                    ),
                ),
                (
                    "minimum_continuous_days",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Min Continuous Days"
                    ),
                ),
                (
                    "medical_certificate_required",
                    models.BooleanField(
                        default=False, verbose_name="Medical Certificate Required"
                    ),
                ),
                (
                    "medical_certificate_min_days",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Medical Certificate Min Days"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="Color"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Leave Type",
                "verbose_name_plural": "Leave Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompensatoryLeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_from_date", models.DateField(verbose_name="Work From Date")),
                ("work_to_date", models.DateField(verbose_name="Work To Date")),
                ("work_end_date", models.DateField(verbose_name="Work End Date")),
                ("reason", models.TextField(verbose_name="Reason for Overtime")),
                ("leave_date", models.DateField(verbose_name="Leave Date")),
                (
                    "half_day",
                    models.BooleanField(default=False, verbose_name="Half Day"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensatory_leaves",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compensatory Leave Request",
                "verbose_name_plural": "Compensatory Leave Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Holiday Name")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "year",
                    models.PositiveIntegerField(default=2025, verbose_name="Year"),
                ),
                (
                    "is_optional",
                    models.BooleanField(default=False, verbose_name="Optional Holiday"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "applies_to_all",
                    models.BooleanField(default=True, verbose_name="Applies to All"),
                ),
                (
                    "regions",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of regions",
                        verbose_name="Regions",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "ordering": ["date"],
                "unique_together": {("name", "date", "year")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeLeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="Effective From")),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective To"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_policies",
                        to="hr.employee",
                    ),
                ),
                (
                    "leave_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leave.leavepolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Leave Policy",
                "verbose_name_plural": "Employee Leave Policies",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="LeaveEncashment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_period_from",
                    models.DateField(verbose_name="Leave Period From"),
                ),
                ("leave_period_to", models.DateField(verbose_name="Leave Period To")),
                ("encashable_days", models.FloatField(verbose_name="Encashable Days")),
                (
                    "encashment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Encashment Amount",
                    ),
                ),
                ("encashment_date", models.DateField(verbose_name="Encashment Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_encashments",
                        to="hr.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leave.leavetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Encashment",
                "verbose_name_plural": "Leave Encashments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField(verbose_name="From Date")),
                ("to_date", models.DateField(verbose_name="To Date")),
                (
                    "total_leave_days",
                    models.FloatField(default=0, verbose_name="Total Leave Days"),
                ),
                (
                    "half_day",
                    models.BooleanField(default=False, verbose_name="Half Day"),
                ),
                (
                    "half_day_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Half Day Date"
                    ),
                ),
                (
                    "leave_session",
                    models.CharField(
                        choices=[
                            ("full_day", "Full Day"),
                            ("first_half", "First Half"),
                            ("second_half", "Second Half"),
                        ],
                        default="full_day",
                        max_length=20,
                        verbose_name="Leave Session",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Reason")),
                (
                    "posting_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Posting Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="leave_documents/",
                        verbose_name="Supporting Document",
                    ),
                ),
                (
                    "medical_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="medical_certificates/",
                        verbose_name="Medical Certificate",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_applications",
                        to="hr.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leave.leavetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Application",
                "verbose_name_plural": "Leave Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeavePolicyLeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annual_allocation",
                    models.FloatField(default=0, verbose_name="Annual Allocation"),
                ),
                (
                    "leave_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_allocations",
                        to="leave.leavepolicy",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_allocations",
                        to="leave.leavetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Policy Allocation",
                "verbose_name_plural": "Leave Policy Allocations",
                "unique_together": {("leave_policy", "leave_type")},
            },
        ),
        migrations.CreateModel(
            name="LeaveAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(default=2025, verbose_name="Year"),
                ),
                (
                    "allocated_days",
                    models.FloatField(default=0, verbose_name="Allocated Days"),
                ),
                ("used_days", models.FloatField(default=0, verbose_name="Used Days")),
                (
                    "carried_forward",
                    models.FloatField(default=0, verbose_name="Carried Forward"),
                ),
                ("from_date", models.DateField(verbose_name="From Date")),
                ("to_date", models.DateField(verbose_name="To Date")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_allocations",
                        to="hr.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leave.leavetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Allocation",
                "verbose_name_plural": "Leave Allocations",
                "ordering": ["-year", "employee", "leave_type"],
                "unique_together": {("employee", "leave_type", "year")},
            },
        ),
    ]
