# Generated by Django 5.2.1 on 2025-10-11 13:54

import core.encrypted_fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zone", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_code",
                    models.CharField(
                        blank=True,
                        help_text="e.g., IDC001, DOC001",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Print ID Card for Worker", max_length=200
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("id_cards", "ID Cards"),
                            ("documents", "Document Processing"),
                            ("permits", "Permits & Licenses"),
                            ("visas", "Visa Services"),
                            ("other", "Other Services"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed service description"
                    ),
                ),
                (
                    "default_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Standard price for this service",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, help_text="For other clients", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Calculated from line items",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax percentage (e.g., 10 for 10%)",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Calculated from subtotal × tax_percentage",
                        max_digits=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Subtotal + tax",
                        max_digits=10,
                    ),
                ),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "reference_document",
                    models.FileField(
                        blank=True,
                        help_text="Upload supporting document (PDF, DOC, DOCX, JPG, PNG)",
                        null=True,
                        upload_to="invoice_documents/%Y/%m/",
                    ),
                ),
                (
                    "reference_document_2",
                    models.FileField(
                        blank=True,
                        help_text="Additional supporting document",
                        null=True,
                        upload_to="invoice_documents/%Y/%m/",
                    ),
                ),
                (
                    "reference_document_3",
                    models.FileField(
                        blank=True,
                        help_text="Additional supporting document",
                        null=True,
                        upload_to="invoice_documents/%Y/%m/",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, help_text="When submitted for approval", null=True
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When approved", null=True
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, help_text="When rejected", null=True
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Reason for rejection"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this invoice",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who rejected this invoice",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted for approval",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="zone.worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashChequeReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "received_from",
                    models.CharField(
                        help_text="Name of person or organization making payment",
                        max_length=200,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("bank_transfer", "Bank Transfer"),
                            ("credit_card", "Credit Card"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        help_text="Method of payment",
                        max_length=50,
                    ),
                ),
                (
                    "amount_in_words",
                    models.CharField(
                        blank=True, help_text="Amount written in words", max_length=300
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount in USD",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_purpose",
                    models.TextField(help_text="Purpose or description of payment"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Check number, transaction ID, or other reference",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related invoice for this receipt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_receipts",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash/Cheque Receipt",
                "verbose_name_plural": "Cash/Cheque Receipts",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfficialReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            (
                                "tax_payment",
                                "Tax Payment to Department of Labour and Vocational Training",
                            ),
                            ("service_fee", "Service Fee Receipt"),
                            ("quota_payment", "Quota Payment Receipt"),
                            ("general", "General Official Receipt"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        blank=True,
                        help_text="Employee No. (e.g., NO.065)",
                        max_length=50,
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(
                        help_text="Employee name (e.g., KHEANG)", max_length=200
                    ),
                ),
                (
                    "total_pass",
                    models.IntegerField(
                        default=0, help_text="Number of passes/permits"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount",
                        max_digits=12,
                    ),
                ),
                (
                    "service_fee_5",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Income Service from Service (5$/p)",
                        max_digits=12,
                    ),
                ),
                (
                    "quota_fee_25",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Income Service from Quota (25$/p)",
                        max_digits=12,
                    ),
                ),
                (
                    "support_document_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Available for used to support document out side",
                        max_digits=12,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(default=2025, help_text="Tax payment year"),
                ),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related invoice for this receipt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_receipts",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Official Receipt",
                "verbose_name_plural": "Official Receipts",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="Current workflow status",
                        max_length=20,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, help_text="Payment date"
                    ),
                ),
                (
                    "payee",
                    models.CharField(
                        help_text="Name of person/organization to be paid",
                        max_length=200,
                    ),
                ),
                (
                    "payee_contact",
                    models.CharField(
                        blank=True, help_text="Phone or email contact", max_length=100
                    ),
                ),
                (
                    "expense_category",
                    models.CharField(
                        choices=[
                            ("office_supplies", "Office Supplies"),
                            ("utilities", "Utilities & Services"),
                            ("permits_licenses", "Permits & Licenses"),
                            ("professional_services", "Professional Services"),
                            ("travel_transport", "Travel & Transportation"),
                            ("maintenance_repairs", "Maintenance & Repairs"),
                            ("marketing", "Marketing & Advertising"),
                            ("employee_benefits", "Employee Benefits"),
                            ("training_development", "Training & Development"),
                            ("insurance", "Insurance"),
                            ("rent_lease", "Rent & Lease"),
                            ("equipment", "Equipment & Technology"),
                            ("workpermit", "Work Permit & Visa Services"),
                            ("government_fees", "Government Fees & Taxes"),
                            ("other", "Other Expenses"),
                        ],
                        default="other",
                        help_text="Category of expense for accounting purposes",
                        max_length=30,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("credit_card", "Credit Card"),
                            ("petty_cash", "Petty Cash"),
                            ("other", "Other"),
                        ],
                        default="bank_transfer",
                        help_text="Method of payment",
                        max_length=20,
                    ),
                ),
                (
                    "amount_in_words",
                    models.CharField(
                        blank=True, help_text="Amount written in words", max_length=300
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Payment amount",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (USD, KHR, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "payment_purpose",
                    models.TextField(
                        help_text="Detailed description of what this payment is for"
                    ),
                ),
                (
                    "supporting_documents",
                    models.TextField(
                        blank=True, help_text="List of supporting documents"
                    ),
                ),
                (
                    "budget_code",
                    models.CharField(
                        blank=True,
                        help_text="Budget or cost center reference",
                        max_length=50,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Bank reference, check number, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "prepared_by",
                    models.CharField(
                        blank=True,
                        help_text="Person who prepared this voucher",
                        max_length=200,
                    ),
                ),
                (
                    "authorised_by",
                    models.CharField(
                        blank=True,
                        help_text="Person who authorized this payment",
                        max_length=200,
                    ),
                ),
                (
                    "received_by",
                    models.CharField(
                        blank=True,
                        help_text="Person who received the payment",
                        max_length=200,
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        blank=True, help_text="Date payment was received", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or special instructions"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, help_text="When submitted for approval", null=True
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When approved", null=True
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, help_text="When rejected", null=True
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Reason for rejection"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="When marked as paid", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this voucher",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related invoice for this payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_vouchers",
                        to="billing.invoice",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who marked as paid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who rejected this voucher",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted for approval",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Voucher",
                "verbose_name_plural": "Payment Vouchers",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentVoucherDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice/Bill"),
                            ("receipt", "Receipt"),
                            ("quotation", "Quotation"),
                            ("contract", "Contract"),
                            ("approval_memo", "Approval Memo"),
                            ("purchase_order", "Purchase Order"),
                            ("delivery_note", "Delivery Note"),
                            ("bank_statement", "Bank Statement"),
                            ("tax_document", "Tax Document"),
                            ("other", "Other Supporting Document"),
                        ],
                        default="other",
                        help_text="Type of reference document",
                        max_length=20,
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        help_text="Name or description of the document", max_length=200
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        help_text="Upload the reference document file",
                        upload_to="payment_voucher_docs/%Y/%m/",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Document number (invoice number, receipt number, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        blank=True, help_text="Date of the document", null=True
                    ),
                ),
                (
                    "document_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount mentioned in the document",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this document"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_documents",
                        to="billing.paymentvoucher",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Voucher Reference Document",
                "verbose_name_plural": "Payment Voucher Reference Documents",
                "ordering": ["-uploaded_at"],
            },
            bases=(core.encrypted_fields.FileEncryptionMixin, models.Model),
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="Service description", max_length=300),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Additional notes for this line item",
                        max_length=300,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="billing.invoice",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the service/item",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Line Item",
                "verbose_name_plural": "Invoice Line Items",
                "ordering": ["invoice", "id"],
            },
        ),
        migrations.CreateModel(
            name="ServiceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("price_changed", "Price Changed"),
                            ("name_changed", "Name Changed"),
                            ("description_changed", "Description Changed"),
                            ("category_changed", "Category Changed"),
                            ("status_changed", "Status Changed"),
                            ("code_changed", "Service Code Changed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the field that changed",
                        max_length=50,
                    ),
                ),
                ("old_value", models.TextField(blank=True, help_text="Previous value")),
                ("new_value", models.TextField(blank=True, help_text="New value")),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the change"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="billing.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service History",
                "verbose_name_plural": "Service Histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="VisaServiceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, help_text="For other clients", max_length=200
                    ),
                ),
                (
                    "duration_months",
                    models.IntegerField(
                        choices=[
                            (1, "1 Month"),
                            (3, "3 Months"),
                            (6, "6 Months"),
                            (12, "1 Year"),
                        ]
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visa_services",
                        to="billing.invoice",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        limit_choices_to={"category": "visas"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.service",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visa_services",
                        to="zone.worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visa Service Record",
                "verbose_name_plural": "Visa Service Records",
                "ordering": ["-created_at"],
            },
        ),
    ]
