# Generated by Django 5.2.1 on 2025-10-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("zone", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("visa", "Visa"),
                            ("visa_regular", "Visa Process (2 Weeks - Building)"),
                            ("work_permit_regular", "Work Permit (25 Days - Building)"),
                            ("visa_express", "Express Visa (3 Days - People)"),
                            (
                                "work_permit_express",
                                "Express Work Permit (15 Days - People)",
                            ),
                            ("passport_renewal", "Passport Renewal"),
                            ("residence_permit", "Residence Permit"),
                            ("business_license", "Business License"),
                            ("id_cards", "ID Cards"),
                            ("other", "Other Document"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("checked", "Checked"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "processing_entity",
                    models.CharField(
                        choices=[
                            ("building", "Government Building Office"),
                            ("people", "People's Office"),
                            ("embassy", "Embassy"),
                            ("consulate", "Consulate"),
                            ("ministry", "Ministry"),
                            ("agent", "Agent"),
                            ("other", "Other"),
                        ],
                        default="building",
                        max_length=20,
                    ),
                ),
                (
                    "government_office",
                    models.CharField(
                        help_text="Name of specific government office", max_length=200
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Government reference/tracking number",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("expected_completion_date", models.DateField(blank=True, null=True)),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Document expiry date", null=True
                    ),
                ),
                (
                    "document_title",
                    models.CharField(
                        blank=True,
                        help_text="Specific document title/name",
                        max_length=200,
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True, help_text="Purpose of document application"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes and comments"
                    ),
                ),
                (
                    "submitted_documents",
                    models.FileField(
                        blank=True,
                        help_text="Scanned copies of submitted documents",
                        null=True,
                        upload_to="document_submissions/",
                    ),
                ),
                (
                    "received_documents",
                    models.FileField(
                        blank=True,
                        help_text="Final received documents",
                        null=True,
                        upload_to="received_documents/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document Submission",
                "verbose_name_plural": "Document Submissions",
                "ordering": ["-submission_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "processing_days",
                    models.IntegerField(help_text="Expected processing time in days"),
                ),
                (
                    "processing_entity",
                    models.CharField(
                        choices=[
                            ("building", "Government Building Office"),
                            ("people", "People's Office"),
                            ("embassy", "Embassy"),
                            ("consulate", "Consulate"),
                            ("ministry", "Ministry"),
                            ("agent", "Agent"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_express", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "required_documents",
                    models.TextField(
                        blank=True, help_text="List of required documents"
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Processing fees",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document Type",
                "verbose_name_plural": "Document Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Change"),
                            ("date_update", "Date Update"),
                            ("reference_added", "Reference Number Added"),
                            ("note_added", "Note Added"),
                            ("document_received", "Document Received"),
                            ("other", "Other Update"),
                        ],
                        max_length=50,
                    ),
                ),
                ("old_value", models.TextField(blank=True, help_text="Previous value")),
                ("new_value", models.TextField(help_text="New value")),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional update notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, help_text="Who made the update", max_length=100
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="document_tracking.documentsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Update",
                "verbose_name_plural": "Document Updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mark",
                    models.CharField(
                        choices=[("New", "New"), ("Renew", "Renew")],
                        default="New",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document_tracking.documentsubmission",
                    ),
                ),
                (
                    "visa_service_charge",
                    models.ForeignKey(
                        blank=True,
                        help_text="Individual visa service charge for this worker",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submission_workers",
                        to="billing.service",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zone.worker"
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Worker",
                "verbose_name_plural": "Submission Workers",
                "unique_together": {("submission", "worker")},
            },
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="workers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select multiple workers for this submission",
                related_name="document_submissions",
                through="document_tracking.SubmissionWorker",
                to="zone.worker",
            ),
        ),
    ]
