@echo off
echo Installing Ruby and Jekyll...
echo 1. Installing Ruby...
winget install RubyInstallerTeam.RubyWithDevKit.3.2 --silent
echo Refreshing environment variables...
call refreshenv
echo 2. Installing Jekyll and Bundler...
gem install jekyll bundler
echo 3. Installing path dependencies...
bundle install
echo Done! You can now run 'jekyll serve'
pause
