# Generated by Django 5.2.1 on 2025-10-11 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(blank=True, max_length=255)),
                ("device_serial", models.CharField(blank=True, max_length=255)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("PassportReader", "Passport Reader"),
                            ("Scanner", "Scanner"),
                        ],
                        default="PassportReader",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("error", "Error"),
                        ],
                        default="disconnected",
                        max_length=20,
                    ),
                ),
                ("version_info", models.CharField(blank=True, max_length=100)),
                ("last_connected", models.DateTimeField(blank=True, null=True)),
                (
                    "websocket_host",
                    models.CharField(default="ws://127.0.0.1:90/echo", max_length=255),
                ),
                ("auto_reconnect", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Device Status",
                "verbose_name_plural": "Device Statuses",
            },
        ),
        migrations.CreateModel(
            name="PassportScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.CharField(max_length=100, unique=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("passport", "Passport"),
                            ("id_card", "ID Card"),
                            ("driver_license", "Driver License"),
                            ("other", "Other"),
                        ],
                        default="passport",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "read_rfid",
                    models.BooleanField(
                        default=True, help_text="Read chip information"
                    ),
                ),
                (
                    "read_viz",
                    models.BooleanField(
                        default=True, help_text="Read visual zone information"
                    ),
                ),
                ("enable_rejection", models.BooleanField(default=False)),
                ("enable_callback", models.BooleanField(default=False)),
                ("detect_card_removal", models.BooleanField(default=False)),
                ("extracted_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sinosecu.devicestatus",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passport_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Passport Scan",
                "verbose_name_plural": "Passport Scans",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("given_names", models.CharField(blank=True, max_length=255)),
                ("surname", models.CharField(blank=True, max_length=255)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("place_of_birth", models.CharField(blank=True, max_length=255)),
                ("document_number", models.CharField(blank=True, max_length=100)),
                ("document_type", models.CharField(blank=True, max_length=50)),
                ("issuing_country", models.CharField(blank=True, max_length=100)),
                ("issuing_authority", models.CharField(blank=True, max_length=255)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("mrz_line1", models.CharField(blank=True, max_length=44)),
                ("mrz_line2", models.CharField(blank=True, max_length=44)),
                ("mrz_line3", models.CharField(blank=True, max_length=44)),
                ("address", models.TextField(blank=True)),
                (
                    "chip_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="RFID chip data"
                    ),
                ),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True, help_text="OCR confidence score", null=True
                    ),
                ),
                (
                    "security_features",
                    models.JSONField(
                        blank=True, default=dict, help_text="Security feature analysis"
                    ),
                ),
                ("additional_fields", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="sinosecu.passportscan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan Result",
                "verbose_name_plural": "Scan Results",
            },
        ),
        migrations.CreateModel(
            name="WebSocketSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_ping", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="sinosecu.devicestatus",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websocket_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WebSocket Session",
                "verbose_name_plural": "WebSocket Sessions",
            },
        ),
        migrations.CreateModel(
            name="ScanImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("White", "White Light"),
                            ("IR", "Infrared"),
                            ("UV", "Ultraviolet"),
                            ("OcrHead", "OCR Head Photo"),
                            ("ChipHead", "Chip Head Photo"),
                            ("SidHead", "Side Head Photo"),
                            ("Full", "Full Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image_data", models.TextField(help_text="Base64 encoded image data")),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Optional file storage path",
                        max_length=500,
                    ),
                ),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="sinosecu.passportscan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan Image",
                "verbose_name_plural": "Scan Images",
                "unique_together": {("scan", "image_type")},
            },
        ),
    ]
