# Generated by Django 5.2.1 on 2025-10-11 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        help_text="Unique zip/postal code", max_length=10, unique=True
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="2-3 letter country code (e.g., KH, US, FR)",
                        max_length=3,
                    ),
                ),
                (
                    "country_name",
                    models.CharField(help_text="Full country name", max_length=100),
                ),
                (
                    "nationality",
                    models.CharField(
                        help_text="Nationality/demonym (e.g., Cambodian, American)",
                        max_length=100,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="Geographic region (e.g., Southeast Asia, Europe)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_nationalities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nationality",
                "verbose_name_plural": "Nationalities",
                "ordering": ["country_name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("probation_ending", "Probation Ending"),
                            ("probation_overdue", "Probation Overdue"),
                            ("document_expiring", "Document Expiring"),
                            ("document_expired", "Document Expired"),
                            ("general", "General"),
                            ("system", "System"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("action_url", models.URLField(blank=True, null=True)),
                ("action_text", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="core_notifi_recipie_aeffaf_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "priority"],
                        name="core_notifi_notific_2ca219_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="core_notifi_created_d0c445_idx"
                    ),
                ],
            },
        ),
    ]
