# Generated by Django 5.2.1 on 2025-10-11 13:54

import core.encrypted_fields
import core.encryption
import django.core.validators
import django.db.models.deletion
import zone.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("address", models.TextField()),
                ("total_floors", models.PositiveIntegerField()),
                ("no_floor", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_buildings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zone_created_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="zone.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor_number", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="zone.building",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_floors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Floor",
                "verbose_name_plural": "Floors",
                "ordering": ["building", "floor_number"],
                "unique_together": {("building", "floor_number")},
            },
        ),
        migrations.CreateModel(
            name="PermissionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_permission_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Category",
                "verbose_name_plural": "Permission Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "level",
                    models.PositiveIntegerField(
                        help_text="Position level in the organization hierarchy"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zone_created_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="zone.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "ordering": ["department", "level", "name"],
                "unique_together": {("name", "department")},
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("manager", "Manager"),
                            ("staff", "Staff"),
                            ("viewer", "Viewer"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "phone_number",
                    core.encryption.EncryptedCharField(
                        blank=True,
                        max_length=1000,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in Cambodia format: +855xxxxxxxx or 0xxxxxxxx (8-10 digits after prefix)",
                                regex="^(\\+?855|0)\\d{8,10}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("position", models.CharField(blank=True, max_length=100)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "worker_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique worker identification number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        help_text="Worker's nickname or preferred name",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KH", "Cambodian"),
                            ("TH", "Thai"),
                            ("VN", "Vietnamese"),
                            ("ID", "Indonesian"),
                            ("MY", "Malaysian"),
                            ("PH", "Filipino"),
                            ("MM", "Myanmar"),
                            ("LA", "Laotian"),
                            ("SG", "Singaporean"),
                            ("BN", "Bruneian"),
                            ("CH", "Chinese"),
                            ("JP", "Japanese"),
                            ("KR", "Korean"),
                            ("TW", "Taiwanese"),
                            ("MO", "Macanese"),
                            ("MN", "Mongolian"),
                            ("IN", "Indian"),
                            ("PK", "Pakistani"),
                            ("BD", "Bangladeshi"),
                            ("LK", "Sri Lankan"),
                            ("NP", "Nepalese"),
                            ("BT", "Bhutanese"),
                            ("MV", "Maldivian"),
                            ("AE", "Emirati"),
                            ("SA", "Saudi"),
                            ("QA", "Qatari"),
                            ("KW", "Kuwaiti"),
                            ("BH", "Bahraini"),
                            ("OM", "Omani"),
                            ("JO", "Jordanian"),
                            ("LB", "Lebanese"),
                            ("SY", "Syrian"),
                            ("IQ", "Iraqi"),
                            ("YE", "Yemeni"),
                            ("IR", "Iranian"),
                            ("TR", "Turkish"),
                            ("GB", "British"),
                            ("FR", "French"),
                            ("DE", "German"),
                            ("IT", "Italian"),
                            ("ES", "Spanish"),
                            ("PT", "Portuguese"),
                            ("NL", "Dutch"),
                            ("BE", "Belgian"),
                            ("CH", "Swiss"),
                            ("SE", "Swedish"),
                            ("NO", "Norwegian"),
                            ("DK", "Danish"),
                            ("FI", "Finnish"),
                            ("RU", "Russian"),
                            ("UA", "Ukrainian"),
                            ("PL", "Polish"),
                            ("GR", "Greek"),
                            ("EG", "Egyptian"),
                            ("ZA", "South African"),
                            ("NG", "Nigerian"),
                            ("KE", "Kenyan"),
                            ("GH", "Ghanaian"),
                            ("ET", "Ethiopian"),
                            ("MA", "Moroccan"),
                            ("DZ", "Algerian"),
                            ("TN", "Tunisian"),
                            ("US", "American"),
                            ("CA", "Canadian"),
                            ("MX", "Mexican"),
                            ("BR", "Brazilian"),
                            ("AR", "Argentine"),
                            ("CL", "Chilean"),
                            ("CO", "Colombian"),
                            ("PE", "Peruvian"),
                            ("CU", "Cuban"),
                            ("AU", "Australian"),
                            ("NZ", "New Zealander"),
                            ("FJ", "Fijian"),
                            ("PG", "Papua New Guinean"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "photo",
                    core.encrypted_fields.EncryptedImageField(
                        blank=True,
                        help_text="Upload worker photo (JPG, PNG, GIF, BMP formats supported) - Automatically encrypted",
                        null=True,
                        upload_to="worker_photos/",
                        validators=[
                            zone.models.validate_image_file_extension,
                            zone.models.validate_image_file_size,
                        ],
                        verbose_name="Photo",
                    ),
                ),
                (
                    "phone_number",
                    core.encryption.EncryptedCharField(
                        blank=True,
                        help_text="Worker's phone number (encrypted)",
                        max_length=1000,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                ("date_joined", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On Leave"),
                            ("probation", "Probation"),
                            ("passed", "Passed"),
                            ("extended", "Extended"),
                            ("failed", "Failed"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "is_vip",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as VIP worker for special privileges",
                    ),
                ),
                (
                    "performance_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Performance rating from 1 (Poor) to 5 (Excellent)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workers",
                        to="zone.building",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workers",
                        to="zone.floor",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workers",
                        to="zone.position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker",
                "verbose_name_plural": "Workers",
                "ordering": ["-date_joined"],
            },
            bases=(core.encrypted_fields.FileEncryptionMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_card", "ID Card"),
                            ("passport", "Passport"),
                            ("visa", "Visa"),
                            ("work_permit", "Work Permit"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_number", models.CharField(max_length=50)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("issuing_authority", models.CharField(max_length=100)),
                (
                    "document_file",
                    core.encrypted_fields.EncryptedFileField(
                        upload_to="worker_documents/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="zone.worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
            bases=(core.encrypted_fields.FileEncryptionMixin, models.Model),
        ),
        migrations.CreateModel(
            name="WorkerChangeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("status_changed", "Status Changed"),
                            ("assigned", "Zone/Building Assigned"),
                            ("probation_started", "Probation Started"),
                            ("probation_passed", "Probation Passed"),
                            ("probation_extended", "Probation Extended"),
                            ("probation_failed", "Probation Failed"),
                            ("document_added", "Document Added"),
                            ("document_updated", "Document Updated"),
                            ("document_deleted", "Document Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the changed field",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, help_text="Previous value", null=True),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, help_text="New value", null=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human readable description of the change",
                        null=True,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_history",
                        to="zone.worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker Change History",
                "verbose_name_plural": "Worker Change History",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkerProbationPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "original_end_date",
                    models.DateField(verbose_name="Original End Date"),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual End Date"
                    ),
                ),
                (
                    "evaluation_notes",
                    models.TextField(blank=True, verbose_name="Evaluation Notes"),
                ),
                (
                    "termination_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for termination during probation",
                        verbose_name="Termination Reason",
                    ),
                ),
                (
                    "terminated_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Termination Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_worker_probation_periods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "terminated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminated_worker_probation_periods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Terminated By",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probation_periods",
                        to="zone.worker",
                        verbose_name="Worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker Probation Period",
                "verbose_name_plural": "Worker Probation Periods",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkerProbationExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extension_duration_days",
                    models.IntegerField(verbose_name="Extension Duration (Days)"),
                ),
                ("reason", models.TextField(verbose_name="Reason for Extension")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_worker_probation_extensions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_worker_probation_extensions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "probation_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="zone.workerprobationperiod",
                        verbose_name="Probation Period",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker Probation Extension",
                "verbose_name_plural": "Worker Probation Extensions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProbationExtensionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extension_duration_days",
                    models.IntegerField(
                        verbose_name="Requested Extension Duration (Days)"
                    ),
                ),
                (
                    "reason",
                    models.TextField(verbose_name="Reason for Extension Request"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Requested At"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "review_comments",
                    models.TextField(
                        blank=True,
                        help_text="Manager comments on approval/rejection",
                        verbose_name="Review Comments",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="probation_extension_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_probation_extension_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "probation_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_requests",
                        to="zone.workerprobationperiod",
                        verbose_name="Probation Period",
                    ),
                ),
            ],
            options={
                "verbose_name": "Probation Extension Request",
                "verbose_name_plural": "Probation Extension Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for the zone",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "phone_number",
                    core.encryption.EncryptedCharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_zones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_worker_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="zone.worker",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_assignments",
                        to="zone.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker Assignment",
                "verbose_name_plural": "Worker Assignments",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="worker",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workers",
                to="zone.zone",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Zone that this building belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buildings",
                to="zone.zone",
            ),
        ),
        migrations.CreateModel(
            name="CustomPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("codename", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_custom_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="zone.permissioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Permission",
                "verbose_name_plural": "Custom Permissions",
                "ordering": ["category", "name"],
                "unique_together": {("name", "category")},
            },
        ),
    ]
