# Generated by Django 5.2.1 on 2025-11-03 09:39

import core.encryption
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zone", "0008_alter_userprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=core.encryption.EncryptedCharField(
                blank=True,
                max_length=1000,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in Cambodia format: +855xxxxxxxx or 0xxxxxxxx (8-10 digits after prefix)",
                        regex="^(\\+?855|0)\\d{8,10}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="phone_number",
            field=core.encryption.EncryptedCharField(
                blank=True,
                help_text="Worker's phone number (encrypted)",
                max_length=1000,
                null=True,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="phone_number",
            field=core.encryption.EncryptedCharField(
                blank=True, max_length=1000, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
