# Generated by Django 5.2.1 on 2025-11-02 13:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0009_alter_employee_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("screening", "Under Screening"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interviewing", "In Interview Process"),
                            ("assessment", "Assessment/Testing"),
                            ("offer_pending", "Offer Pending Approval"),
                            ("offer_extended", "Offer Extended"),
                            ("offer_accepted", "Offer Accepted"),
                            ("offer_rejected", "Offer Rejected by Candidate"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("on_hold", "On Hold"),
                        ],
                        default="applied",
                        max_length=30,
                        verbose_name="Application Status",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="recruitment/resumes/",
                        verbose_name="Resume",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(blank=True, verbose_name="Cover Letter"),
                ),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Expected Salary",
                    ),
                ),
                (
                    "notice_period",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Notice Period"
                    ),
                ),
                (
                    "availability_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Availability Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Internal Notes")),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "reference_check_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Reference Check"
                    ),
                ),
                (
                    "background_check_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Background Check"
                    ),
                ),
                (
                    "hired_date",
                    models.DateField(blank=True, null=True, verbose_name="Hired Date"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rejected At"
                    ),
                ),
                (
                    "applied_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Applied Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "hired_as_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recruitment_source",
                        to="hr.employee",
                        verbose_name="Employee Record",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_candidates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate",
                "verbose_name_plural": "Candidates",
                "ordering": ["-applied_date"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Test"),
                            ("aptitude", "Aptitude Test"),
                            ("personality", "Personality Assessment"),
                            ("skill", "Skill Assessment"),
                            ("case_study", "Case Study"),
                            ("coding", "Coding Challenge"),
                        ],
                        max_length=20,
                        verbose_name="Assessment Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("evaluated", "Evaluated"),
                            ("expired", "Expired"),
                        ],
                        default="assigned",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Instructions"),
                ),
                (
                    "assigned_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Assigned Date"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Due Date"
                    ),
                ),
                (
                    "submitted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted Date"
                    ),
                ),
                (
                    "file_submission",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="recruitment/assessments/",
                        verbose_name="Submission File",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Score",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="Maximum Score",
                    ),
                ),
                (
                    "evaluator_notes",
                    models.TextField(blank=True, verbose_name="Evaluator Notes"),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Evaluated At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluated_assessments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Evaluated By",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="recruitment.candidate",
                        verbose_name="Candidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessments",
                "ordering": ["-assigned_date"],
            },
        ),
        migrations.CreateModel(
            name="CandidateStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Old Status"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(max_length=30, verbose_name="New Status"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="recruitment.candidate",
                        verbose_name="Candidate",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status History",
                "verbose_name_plural": "Status Histories",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone_screening", "Phone Screening"),
                            ("technical", "Technical Interview"),
                            ("hr", "HR Interview"),
                            ("manager", "Manager Interview"),
                            ("panel", "Panel Interview"),
                            ("final", "Final Interview"),
                        ],
                        max_length=20,
                        verbose_name="Interview Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("scheduled_date", models.DateTimeField(verbose_name="Scheduled Date")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Duration (minutes)"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Location"
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(blank=True, verbose_name="Meeting Link"),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="Feedback")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                        verbose_name="Rating",
                    ),
                ),
                ("strengths", models.TextField(blank=True, verbose_name="Strengths")),
                ("weaknesses", models.TextField(blank=True, verbose_name="Weaknesses")),
                (
                    "recommendation",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Recommendation"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="recruitment.candidate",
                        verbose_name="Candidate",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_interviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Interviewer",
                    ),
                ),
                (
                    "panel_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="panel_interviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Panel Members",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview",
                "verbose_name_plural": "Interviews",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("sent", "Sent to Candidate"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Salary"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Bonus",
                    ),
                ),
                ("benefits", models.TextField(blank=True, verbose_name="Benefits")),
                (
                    "employment_type",
                    models.CharField(
                        default="Full-time",
                        max_length=50,
                        verbose_name="Employment Type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Proposed Start Date")),
                (
                    "probation_period_months",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Probation Period (Months)"
                    ),
                ),
                (
                    "offer_letter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="recruitment/offers/",
                        verbose_name="Offer Letter",
                    ),
                ),
                (
                    "offer_sent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Offer Sent Date"
                    ),
                ),
                (
                    "offer_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Offer Expiry Date"
                    ),
                ),
                (
                    "candidate_response",
                    models.TextField(blank=True, verbose_name="Candidate Response"),
                ),
                (
                    "response_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Response Date"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Internal Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_offers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="recruitment.candidate",
                        verbose_name="Candidate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_offers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "position_offered",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.position",
                        verbose_name="Position Offered",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Offer",
                "verbose_name_plural": "Job Offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Job Title")),
                ("description", models.TextField(verbose_name="Job Description")),
                ("requirements", models.TextField(verbose_name="Requirements")),
                (
                    "responsibilities",
                    models.TextField(blank=True, verbose_name="Responsibilities"),
                ),
                (
                    "qualifications",
                    models.TextField(blank=True, verbose_name="Qualifications"),
                ),
                (
                    "salary_range_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Salary Range Min",
                    ),
                ),
                (
                    "salary_range_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Salary Range Max",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        default="Full-time",
                        max_length=50,
                        verbose_name="Employment Type",
                    ),
                ),
                (
                    "vacancies",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Number of Vacancies"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("on_hold", "On Hold"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "posted_date",
                    models.DateField(blank=True, null=True, verbose_name="Posted Date"),
                ),
                (
                    "closing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Closing Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to="hr.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to="hr.position",
                        verbose_name="Position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
                "ordering": ["-posted_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="job_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="recruitment.jobposting",
                verbose_name="Job Posting",
            ),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewing", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("interview", "Interview Scheduled"),
                            ("rejected", "Rejected"),
                            ("accepted", "Accepted"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "applied_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Applied Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legacy_reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_applications",
                        to="recruitment.candidate",
                        verbose_name="Candidate",
                    ),
                ),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_applications",
                        to="recruitment.jobposting",
                        verbose_name="Job Posting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application (Legacy)",
                "verbose_name_plural": "Applications (Legacy)",
                "ordering": ["-applied_date"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={("email", "job_posting")},
        ),
    ]
