# Generated by Django 5.2.1 on 2025-11-04 02:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0016_alter_employee_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap icon class (e.g., bi-lightbulb)",
                        max_length=50,
                        verbose_name="Icon Class",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="primary",
                        help_text="Bootstrap color class",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Suggestion Category",
                "verbose_name_plural": "Suggestion Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("suggestion", "Suggestion"),
                            ("feedback", "Feedback"),
                            ("complaint", "Complaint"),
                            ("appreciation", "Appreciation"),
                            ("idea", "Idea/Innovation"),
                        ],
                        default="suggestion",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description/Details")),
                (
                    "expected_outcome",
                    models.TextField(
                        blank=True,
                        help_text="What positive changes do you expect from this suggestion?",
                        verbose_name="Expected Outcome/Benefit",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Supporting documents, images, etc.",
                        null=True,
                        upload_to="suggestions/%Y/%m/",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("implemented", "Implemented"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="Your identity will be hidden from other employees",
                        verbose_name="Submit Anonymously",
                    ),
                ),
                (
                    "response",
                    models.TextField(blank=True, verbose_name="Management Response"),
                ),
                (
                    "response_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Response Date"
                    ),
                ),
                (
                    "implementation_notes",
                    models.TextField(blank=True, verbose_name="Implementation Notes"),
                ),
                (
                    "implementation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Implementation Date"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Estimated Cost",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Actual Cost",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Employee satisfaction with the response (1-5)",
                        null=True,
                        verbose_name="Rating",
                    ),
                ),
                ("upvotes", models.IntegerField(default=0, verbose_name="Upvotes")),
                ("views", models.IntegerField(default=0, verbose_name="Views")),
                (
                    "submitted_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Submitted Date"
                    ),
                ),
                (
                    "reviewed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed Date"
                    ),
                ),
                (
                    "closed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Closed Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "affected_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions",
                        to="hr.department",
                        verbose_name="Affected Department",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_suggestions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="hr.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "response_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responded_suggestions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Response By",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions",
                        to="suggestions.suggestioncategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suggestion",
                "verbose_name_plural": "Suggestions",
                "ordering": ["-submitted_date"],
                "permissions": [
                    ("can_manage_suggestions", "Can manage all suggestions"),
                    ("can_respond_to_suggestions", "Can respond to suggestions"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SuggestionComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Comment")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Only visible to management",
                        verbose_name="Internal Note",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="suggestions.suggestion",
                        verbose_name="Suggestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestion_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suggestion Comment",
                "verbose_name_plural": "Suggestion Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SuggestionStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(max_length=20, verbose_name="Old Status"),
                ),
                (
                    "new_status",
                    models.CharField(max_length=20, verbose_name="New Status"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="suggestions.suggestion",
                        verbose_name="Suggestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status History",
                "verbose_name_plural": "Status Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SuggestionVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestion_votes",
                        to="hr.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="suggestions.suggestion",
                        verbose_name="Suggestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suggestion Vote",
                "verbose_name_plural": "Suggestion Votes",
                "ordering": ["-created_at"],
                "unique_together": {("suggestion", "employee")},
            },
        ),
    ]
