# Generated by Django 5.2.1 on 2025-10-11 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Workflow Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Minimum Amount",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Maximum Amount",
                    ),
                ),
                (
                    "level_1_type",
                    models.CharField(
                        choices=[
                            ("manager", "Manager Approval"),
                            ("finance", "Finance Approval"),
                            ("ceo", "CEO Approval"),
                            ("custom", "Custom Approval"),
                        ],
                        max_length=20,
                        verbose_name="Level 1 Type",
                    ),
                ),
                (
                    "level_2_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manager", "Manager Approval"),
                            ("finance", "Finance Approval"),
                            ("ceo", "CEO Approval"),
                            ("custom", "Custom Approval"),
                        ],
                        max_length=20,
                        verbose_name="Level 2 Type",
                    ),
                ),
                (
                    "level_3_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manager", "Manager Approval"),
                            ("finance", "Finance Approval"),
                            ("ceo", "CEO Approval"),
                            ("custom", "Custom Approval"),
                        ],
                        max_length=20,
                        verbose_name="Level 3 Type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Expense Approval Workflow",
                "verbose_name_plural": "Expense Approval Workflows",
                "ordering": ["min_amount"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category Name"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Category Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "requires_receipt",
                    models.BooleanField(default=True, verbose_name="Requires Receipt"),
                ),
                (
                    "max_amount_per_claim",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Max Amount Per Claim",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(default=True, verbose_name="Requires Approval"),
                ),
                (
                    "gl_account",
                    models.CharField(
                        blank=True,
                        help_text="General Ledger account for ERPNext integration",
                        max_length=50,
                        verbose_name="GL Account",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claim_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Claim ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Claim Title")),
                ("purpose", models.TextField(blank=True, verbose_name="Purpose")),
                ("expense_date", models.DateField(verbose_name="Expense Date")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("manager_approved", "Manager Approved"),
                            ("finance_approved", "Finance Approved"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "manager_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Manager Approved At"
                    ),
                ),
                (
                    "finance_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finance Approved At"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rejected At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=50,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Payment Reference"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid At"),
                ),
                (
                    "erp_expense_claim_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP Expense Claim ID"
                    ),
                ),
                (
                    "erp_journal_entry_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP Journal Entry ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Expense Claim",
                "verbose_name_plural": "Expense Claims",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseClaimLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                ("expense_date", models.DateField(verbose_name="Expense Date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Unit Cost",
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expense_receipts/",
                        verbose_name="Receipt",
                    ),
                ),
                (
                    "additional_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expense_documents/",
                        verbose_name="Additional Document",
                    ),
                ),
                (
                    "erp_expense_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP Expense Type"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Expense Claim Line Item",
                "verbose_name_plural": "Expense Claim Line Items",
                "ordering": ["expense_date"],
            },
        ),
        migrations.CreateModel(
            name="ExpensePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Policy Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "applies_to_all_employees",
                    models.BooleanField(
                        default=True, verbose_name="Applies to All Employees"
                    ),
                ),
                (
                    "max_amount_per_claim",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Max Amount Per Claim",
                    ),
                ),
                (
                    "max_amount_per_month",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Max Amount Per Month",
                    ),
                ),
                (
                    "max_amount_per_year",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Max Amount Per Year",
                    ),
                ),
                (
                    "auto_approve_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Auto Approve Limit",
                    ),
                ),
                (
                    "requires_manager_approval",
                    models.BooleanField(
                        default=True, verbose_name="Requires Manager Approval"
                    ),
                ),
                (
                    "requires_finance_approval",
                    models.BooleanField(
                        default=False, verbose_name="Requires Finance Approval"
                    ),
                ),
                (
                    "finance_approval_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000,
                        max_digits=12,
                        verbose_name="Finance Approval Limit",
                    ),
                ),
                (
                    "receipt_required",
                    models.BooleanField(default=True, verbose_name="Receipt Required"),
                ),
                (
                    "receipt_required_above",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Receipt Required Above",
                    ),
                ),
                (
                    "claim_deadline_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Days after expense date to submit claim",
                        verbose_name="Claim Deadline (Days)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Expense Policy",
                "verbose_name_plural": "Expense Policies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AdvanceRecovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recovery_date", models.DateField(verbose_name="Recovery Date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "recovery_method",
                    models.CharField(
                        choices=[
                            ("salary_deduction", "Salary Deduction"),
                            ("cash_payment", "Cash Payment"),
                        ],
                        max_length=50,
                        verbose_name="Recovery Method",
                    ),
                ),
                (
                    "salary_slip_reference",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Salary Slip Reference"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Advance Recovery",
                "verbose_name_plural": "Advance Recoveries",
                "ordering": ["-recovery_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advance_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Advance ID",
                    ),
                ),
                ("purpose", models.TextField(verbose_name="Purpose")),
                (
                    "requested_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Requested Amount"
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Approved Amount",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Paid Amount",
                    ),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Outstanding Amount",
                    ),
                ),
                (
                    "recovered_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Recovered Amount",
                    ),
                ),
                (
                    "recovery_method",
                    models.CharField(
                        choices=[
                            ("salary_deduction", "Salary Deduction"),
                            ("lump_sum", "Lump Sum"),
                            ("installments", "Installments"),
                        ],
                        default="salary_deduction",
                        max_length=20,
                        verbose_name="Recovery Method",
                    ),
                ),
                (
                    "recovery_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Recovery Start Date"
                    ),
                ),
                (
                    "number_of_installments",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Number of Installments"
                    ),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Installment Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("fully_recovered", "Fully Recovered"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rejected At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Payment Method"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Payment Reference"
                    ),
                ),
                (
                    "erp_employee_advance_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="ERP Employee Advance ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_employee_advances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_advances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Advance",
                "verbose_name_plural": "Employee Advances",
                "ordering": ["-created_at"],
            },
        ),
    ]
