# Generated by Django 5.2.1 on 2025-10-11 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeadvance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_advances",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeeadvance",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_advance_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeeadvance",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_advances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="advancerecovery",
            name="advance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recoveries",
                to="expenses.employeeadvance",
            ),
        ),
        migrations.AddField(
            model_name="expenseapprovalworkflow",
            name="level_1_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="level1_workflows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Level 1 Approver",
            ),
        ),
        migrations.AddField(
            model_name="expenseapprovalworkflow",
            name="level_2_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="level2_workflows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Level 2 Approver",
            ),
        ),
        migrations.AddField(
            model_name="expenseapprovalworkflow",
            name="level_3_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="level3_workflows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Level 3 Approver",
            ),
        ),
        migrations.AddField(
            model_name="expenseapprovalworkflow",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                to="expenses.expensecategory",
                verbose_name="Applicable Categories",
            ),
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_expense_claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_claims",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="finance_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finance_approved_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="manager_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manager_approved_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_expense_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expenseclaimlineitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="expenses.expensecategory",
            ),
        ),
        migrations.AddField(
            model_name="expenseclaimlineitem",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="expenses.expenseclaim",
            ),
        ),
        migrations.AddField(
            model_name="expensepolicy",
            name="applicable_departments",
            field=models.ManyToManyField(
                blank=True, to="hr.department", verbose_name="Applicable Departments"
            ),
        ),
        migrations.AddField(
            model_name="expensepolicy",
            name="applicable_positions",
            field=models.ManyToManyField(
                blank=True, to="hr.position", verbose_name="Applicable Positions"
            ),
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_claims",
                to="expenses.expensepolicy",
            ),
        ),
    ]
