# Generated by Django 5.2.1 on 2025-10-11 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0001_initial"),
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="timecardentry",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timecard_entries",
                to="project.project",
                verbose_name="Project",
            ),
        ),
        migrations.AddField(
            model_name="timecardentry",
            name="timecard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="hr.timecard",
                verbose_name="Timecard",
            ),
        ),
        migrations.AddField(
            model_name="timecardentry",
            name="timesheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timecard_entries",
                to="project.timesheet",
                verbose_name="Timesheet",
            ),
        ),
        migrations.AddField(
            model_name="overtimeclaim",
            name="timecard_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="overtime_claims",
                to="hr.timecardentry",
            ),
        ),
        migrations.AddField(
            model_name="yearendstatement",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="year_end_statements",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="yearendstatement",
            name="generated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_statements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="employeechangehistory",
            index=models.Index(
                fields=["employee", "-timestamp"], name="hr_employee_employe_91ebe1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeechangehistory",
            index=models.Index(
                fields=["action", "-timestamp"], name="hr_employee_action_2a4e40_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeesalarycomponent",
            unique_together={("employee_salary", "payroll_component")},
        ),
        migrations.AlterUniqueTogether(
            name="payrollperiod",
            unique_together={("payroll_policy", "start_date", "end_date")},
        ),
        migrations.AlterUniqueTogether(
            name="employeesalary",
            unique_together={("employee", "effective_date")},
        ),
        migrations.AlterUniqueTogether(
            name="payrollrun",
            unique_together={("payroll_period", "run_number")},
        ),
        migrations.AlterUniqueTogether(
            name="payrollentry",
            unique_together={("payroll_run", "employee")},
        ),
        migrations.AlterUniqueTogether(
            name="timecard",
            unique_together={("employee", "year", "month")},
        ),
        migrations.AddIndex(
            model_name="overtimeclaim",
            index=models.Index(
                fields=["employee", "work_date"], name="hr_overtime_employe_bc171b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="overtimeclaim",
            index=models.Index(
                fields=["status", "work_date"], name="hr_overtime_status_d0ce9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="overtimeclaim",
            index=models.Index(
                fields=["payroll_period"], name="hr_overtime_payroll_edd1c1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="yearendstatement",
            unique_together={("employee", "financial_year")},
        ),
    ]
