# Generated by Django 5.2.1 on 2025-11-01 05:43

import core.encryption
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def clear_branch_data(apps, schema_editor):
    """Clear existing branch data (CharField values) before converting to ForeignKey"""
    # Use raw SQL to handle the conversion safely
    with schema_editor.connection.cursor() as cursor:
        # First, make the column nullable
        cursor.execute(
            "ALTER TABLE hr_employee ALTER COLUMN branch DROP NOT NULL;"
        )
        # Then clear all branch values
        cursor.execute(
            "UPDATE hr_employee SET branch = NULL WHERE branch = '' OR branch IS NOT NULL;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_add_branch_model"),
        ("hr", "0007_alter_employee_email_and_more"),
    ]

    operations = [
        # First, clear the existing branch data
        migrations.RunPython(clear_branch_data, reverse_code=migrations.RunPython.noop),

        # Remove the old branch field
        migrations.RemoveField(
            model_name="employee",
            name="branch",
        ),

        # Add the new branch field as ForeignKey
        migrations.AddField(
            model_name="employee",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="company.branch",
                verbose_name="Branch",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=core.encryption.EncryptedEmailField(
                blank=True, max_length=1016, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_name",
            field=core.encryption.EncryptedCharField(
                max_length=1000, verbose_name="Emergency Contact Name"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_phone",
            field=core.encryption.EncryptedCharField(
                max_length=1000,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in Cambodia format: +855xxxxxxxx or 0xxxxxxxx (8-10 digits after prefix)",
                        regex="^(\\+?855|0)\\d{8,10}$",
                    )
                ],
                verbose_name="Emergency Contact Phone",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=core.encryption.EncryptedCharField(
                blank=True,
                max_length=1000,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in Cambodia format: +855xxxxxxxx or 0xxxxxxxx (8-10 digits after prefix)",
                        regex="^(\\+?855|0)\\d{8,10}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
    ]
