# Generated by Django 5.2.1 on 2025-11-05 06:17

import core.encryption
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0017_alter_employee_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=core.encryption.EncryptedEmailField(
                blank=True, max_length=1016, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_name",
            field=core.encryption.EncryptedCharField(
                max_length=1000, verbose_name="Emergency Contact Name"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_phone",
            field=core.encryption.EncryptedCharField(
                max_length=1000,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in Cambodia format: +855xxxxxxxx or 0xxxxxxxx (8-10 digits after prefix)",
                        regex="^(\\+?855|0)\\d{8,10}$",
                    )
                ],
                verbose_name="Emergency Contact Phone",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=core.encryption.EncryptedCharField(
                blank=True,
                max_length=1000,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in Cambodia format: +855xxxxxxxx or 0xxxxxxxx (8-10 digits after prefix)",
                        regex="^(\\+?855|0)\\d{8,10}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="employeechangehistory",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_history",
                to="hr.employee",
            ),
        ),
    ]
