# Generated by Django 5.2.1 on 2025-10-11 13:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auditlog", "0017_add_actor_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("logging_failure", "Audit Logging Failed"),
                            ("permission_denied", "Permission Denied"),
                            ("data_corruption", "Data Corruption Detected"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("system_error", "System Error"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("error_message", models.TextField(blank=True)),
                ("stack_trace", models.TextField(blank=True)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_audit_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Exception",
                "verbose_name_plural": "Audit Exceptions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AuditReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("user_activity", "User Activity Report"),
                            ("data_changes", "Data Changes Report"),
                            ("security_events", "Security Events Report"),
                            ("compliance", "Compliance Report"),
                            ("risk_assessment", "Risk Assessment Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("date_from", models.DateTimeField()),
                ("date_to", models.DateTimeField()),
                ("resource_types", models.JSONField(blank=True, default=list)),
                ("action_types", models.JSONField(blank=True, default=list)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("on_demand", "On Demand"),
                        ],
                        default="on_demand",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_generated", models.DateTimeField(blank=True, null=True)),
                ("next_generation", models.DateTimeField(blank=True, null=True)),
                ("file_path", models.FileField(blank=True, upload_to="audit_reports/")),
                ("record_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_audit_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="audit_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Report",
                "verbose_name_plural": "Audit Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Session",
                "verbose_name_plural": "Audit Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("create", "Record Created"),
                            ("update", "Record Updated"),
                            ("delete", "Record Deleted"),
                            ("view", "Record Viewed"),
                            ("export", "Data Exported"),
                            ("import", "Data Imported"),
                            ("permission_change", "Permission Changed"),
                            ("configuration_change", "System Configuration Changed"),
                            ("security_event", "Security Event"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                ("resource_name", models.TextField(blank=True)),
                ("description", models.TextField()),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("business_unit", models.CharField(blank=True, max_length=100)),
                (
                    "correlation_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("risk_score", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "log_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enhanced_audit",
                        to="auditlog.logentry",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="audit_management.auditsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Trail",
                "verbose_name_plural": "Audit Trails",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_manag_user_id_d9d797_idx",
                    ),
                    models.Index(
                        fields=["action_type", "timestamp"],
                        name="audit_manag_action__5bb065_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "timestamp"],
                        name="audit_manag_resourc_27ef14_idx",
                    ),
                    models.Index(
                        fields=["severity", "timestamp"],
                        name="audit_manag_severit_2fc821_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="audit_manag_correla_728375_idx"
                    ),
                    models.Index(
                        fields=["risk_score"], name="audit_manag_risk_sc_ca4581_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SimpleAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                        ],
                        max_length=20,
                        verbose_name="What Action",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="What Model"),
                ),
                ("object_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "object_name",
                    models.CharField(
                        blank=True,
                        help_text="Human readable name of the object",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(verbose_name="What Changed")),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="When",
                    ),
                ),
                (
                    "old_values",
                    models.TextField(
                        blank=True, help_text="Old values (for updates)", null=True
                    ),
                ),
                (
                    "new_values",
                    models.TextField(
                        blank=True, help_text="New values (for updates)", null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Who",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simple Audit Log",
                "verbose_name_plural": "Simple Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_manag_user_id_60cd13_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="audit_manag_action_36468a_idx",
                    ),
                    models.Index(
                        fields=["model_name", "-timestamp"],
                        name="audit_manag_model_n_9a33ac_idx",
                    ),
                ],
            },
        ),
    ]
