# Generated by Django 5.2.1 on 2025-10-11 13:54

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NSSFConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("OCCUPATIONAL_RISK", "Occupational Risk"),
                            ("HEALTH_CARE", "Health Care"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "employee_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Employee contribution rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "employer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Employer contribution rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "max_salary_cap",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum salary for calculation",
                        max_digits=12,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "docstatus",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Submitted"), (2, "Cancelled")],
                        default=0,
                    ),
                ),
                ("salary_slip_based_on_timesheet", models.BooleanField(default=False)),
                (
                    "hour_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("leave_encashment", models.BooleanField(default=False)),
                (
                    "max_benefits",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaxSlab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "fixed_tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["min_amount"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "loan_term_months",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "monthly_installment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("DEFAULTED", "Defaulted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("purpose", models.TextField()),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="hr.employee",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        blank=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "housing_allowance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "meal_allowance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "phone_allowance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "seniority_allowance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("bank_account_name", models.CharField(blank=True, max_length=100)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("BANK", "Bank Transfer"),
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                        ],
                        default="BANK",
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField(default=datetime.date.today)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_info",
                        to="hr.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=100)),
                (
                    "payroll_frequency",
                    models.CharField(default="Monthly", max_length=20),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("posting_date", models.DateField(default=datetime.date.today)),
                ("salary_slips_created", models.BooleanField(default=False)),
                ("salary_slips_submitted", models.BooleanField(default=False)),
                ("bank_entries_made", models.BooleanField(default=False)),
                ("validate_attendance", models.BooleanField(default=True)),
                (
                    "docstatus",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Submitted"), (2, "Cancelled")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.department",
                    ),
                ),
                ("employees", models.ManyToManyField(blank=True, to="hr.employee")),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("SEMI_MONTHLY", "Semi-Monthly"),
                            ("WEEKLY", "Weekly"),
                            ("BI_WEEKLY", "Bi-Weekly"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("payment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROCESSING", "Processing"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "unique_together": {("start_date", "end_date")},
            },
        ),
        migrations.CreateModel(
            name="SalaryAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("request_date", models.DateField(default=datetime.date.today)),
                ("approval_date", models.DateField(blank=True, null=True)),
                (
                    "repayment_method",
                    models.CharField(
                        choices=[
                            ("ONE_TIME", "One Time Deduction"),
                            ("INSTALLMENTS", "Monthly Installments"),
                        ],
                        default="ONE_TIME",
                        max_length=20,
                    ),
                ),
                (
                    "installment_months",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("PAID", "Paid"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_advances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_advances",
                        to="hr.employee",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_advances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="SalaryComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(blank=True, max_length=10)),
                (
                    "component_type",
                    models.CharField(
                        choices=[("EARNING", "Earning"), ("DEDUCTION", "Deduction")],
                        max_length=20,
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Amount"),
                            ("PERCENTAGE", "Percentage"),
                            ("FORMULA", "Formula Based"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_payable",
                    models.BooleanField(
                        default=True, help_text="Whether this component should be paid"
                    ),
                ),
                (
                    "depends_on_payment_days",
                    models.BooleanField(
                        default=False, help_text="Calculate based on working days"
                    ),
                ),
                (
                    "depends_on_timesheet",
                    models.BooleanField(
                        default=False, help_text="Calculate based on timesheet data"
                    ),
                ),
                (
                    "is_tax_applicable",
                    models.BooleanField(
                        default=True, help_text="Include in tax calculations"
                    ),
                ),
                (
                    "is_additional_component",
                    models.BooleanField(
                        default=False, help_text="Can only be paid as additional salary"
                    ),
                ),
                (
                    "is_statistical_component",
                    models.BooleanField(
                        default=False,
                        help_text="For information only, not included in totals",
                    ),
                ),
                (
                    "variable_based_on_taxable_salary",
                    models.BooleanField(
                        default=False, help_text="Standard tax deduction component"
                    ),
                ),
                (
                    "formula",
                    models.TextField(
                        blank=True,
                        help_text="Python expression for calculation (e.g., base * 0.1)",
                    ),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True,
                        help_text="Python expression for when to apply (e.g., grade == 'Manager')",
                    ),
                ),
                (
                    "round_to_nearest",
                    models.IntegerField(
                        default=0,
                        help_text="Round amount to nearest value (0 = no rounding)",
                    ),
                ),
                (
                    "max_benefit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum yearly benefit amount",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("pay_against_benefit_claim", models.BooleanField(default=False)),
                (
                    "percentage_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "percentage_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payroll.salarycomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AdditionalSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payroll_date",
                    models.DateField(
                        help_text="Date when this should be included in payroll"
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "to_date",
                    models.DateField(
                        blank=True,
                        help_text="End date for recurring additional salary",
                        null=True,
                    ),
                ),
                ("ref_doctype", models.CharField(blank=True, max_length=50)),
                ("ref_docname", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_salaries",
                        to="hr.employee",
                    ),
                ),
                (
                    "salary_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.salarycomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["-payroll_date"],
            },
        ),
        migrations.CreateModel(
            name="SalarySlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("posting_date", models.DateField(default=datetime.date.today)),
                ("total_working_days", models.IntegerField(default=0)),
                ("payment_days", models.IntegerField(default=0)),
                ("leave_without_pay", models.IntegerField(default=0)),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "gross_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "total_deduction",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "rounded_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "hour_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_working_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "docstatus",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Submitted"), (2, "Cancelled")],
                        default=0,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CALCULATED", "Calculated"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=20)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_slips",
                        to="hr.employee",
                    ),
                ),
                (
                    "payroll_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_slips",
                        to="payroll.payrollperiod",
                    ),
                ),
                (
                    "salary_structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.salarystructure",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "employee__employee_id"],
                "unique_together": {("payroll_period", "employee")},
            },
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "billable_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "docstatus",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Submitted"), (2, "Cancelled")],
                        default=0,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_timesheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_timesheets",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timesheet",
                "verbose_name_plural": "Timesheets",
                "db_table": "payroll_timesheet",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TimesheetDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity", models.CharField(max_length=200)),
                ("from_time", models.DateTimeField()),
                ("to_time", models.DateTimeField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=4)),
                ("project", models.CharField(blank=True, max_length=100)),
                ("task", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("billable", models.BooleanField(default=True)),
                (
                    "billing_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "timesheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="payroll.timesheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timesheet Detail",
                "verbose_name_plural": "Timesheet Details",
                "db_table": "payroll_timesheet_detail",
                "ordering": ["from_time"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_benefit_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "claimed_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "remaining_benefit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="hr.employee",
                    ),
                ),
                (
                    "payroll_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.payrollperiod",
                    ),
                ),
                (
                    "earning_component",
                    models.ForeignKey(
                        limit_choices_to={"component_type": "EARNING"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.salarycomponent",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("employee", "earning_component", "payroll_period")
                },
            },
        ),
        migrations.CreateModel(
            name="PayrollDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.salarycomponent",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_details",
                        to="payroll.salaryslip",
                    ),
                ),
            ],
            options={
                "ordering": ["component__display_order"],
                "unique_together": {("payroll", "component")},
            },
        ),
        migrations.CreateModel(
            name="SalarySlipDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "default_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("depends_on_payment_days", models.BooleanField(default=False)),
                (
                    "salary_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.salarycomponent",
                    ),
                ),
                (
                    "salary_slip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="payroll.salaryslip",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "salary_component__display_order",
                    "salary_component__name",
                ],
                "unique_together": {("salary_slip", "salary_component")},
            },
        ),
        migrations.CreateModel(
            name="SalaryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "formula",
                    models.TextField(
                        blank=True, help_text="Override component formula"
                    ),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True, help_text="Override component condition"
                    ),
                ),
                ("statistical_component", models.BooleanField(default=False)),
                (
                    "salary_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.salarycomponent",
                    ),
                ),
                (
                    "salary_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_details",
                        to="payroll.salarystructure",
                    ),
                ),
            ],
            options={
                "ordering": ["salary_component__display_order"],
                "unique_together": {("salary_structure", "salary_component")},
            },
        ),
        migrations.CreateModel(
            name="SalaryStructureAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField(blank=True, null=True)),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base amount for percentage calculations",
                        max_digits=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "docstatus",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Submitted"), (2, "Cancelled")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_assignments",
                        to="hr.employee",
                    ),
                ),
                (
                    "salary_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.salarystructure",
                    ),
                ),
            ],
            options={
                "ordering": ["-from_date"],
                "unique_together": {("employee", "from_date")},
            },
        ),
    ]
