# Generated by Django 5.2.1 on 2025-10-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar ($)"),
                            ("KHR", "Cambodian Riel (៛)"),
                            ("EUR", "Euro (€)"),
                            ("GBP", "British Pound (£)"),
                            ("JPY", "Japanese Yen (¥)"),
                            ("CNY", "Chinese Yuan (¥)"),
                            ("THB", "Thai Baht (฿)"),
                            ("VND", "Vietnamese Dong (₫)"),
                        ],
                        default="USD",
                        help_text="Primary currency for payroll calculations",
                        max_length=3,
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(
                        default="$",
                        help_text="Symbol to display (e.g., $, ៛, €)",
                        max_length=10,
                    ),
                ),
                (
                    "currency_position",
                    models.CharField(
                        choices=[
                            ("before", "Before amount ($100)"),
                            ("after", "After amount (100$)"),
                        ],
                        default="before",
                        help_text="Where to display currency symbol",
                        max_length=10,
                    ),
                ),
                (
                    "decimal_places",
                    models.IntegerField(
                        choices=[
                            (0, "No decimals (e.g., 1000)"),
                            (2, "Two decimals (e.g., 1000.00)"),
                        ],
                        default=2,
                        help_text="Number of decimal places to display",
                    ),
                ),
                (
                    "use_thousand_separator",
                    models.BooleanField(
                        default=True,
                        help_text="Use comma separator for thousands (e.g., 1,000,000)",
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payroll Settings",
                "verbose_name_plural": "Payroll Settings",
            },
        ),
    ]
