# Generated by Django 5.2.1 on 2025-10-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_add_payroll_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeesalary",
            name="basic_salary",
        ),
    ]
