# Generated by Django 5.2.1 on 2025-10-18 05:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_remove_employeesalary_basic_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryslip",
            name="overtime_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Total overtime hours for this period",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="salaryslip",
            name="overtime_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.5"),
                help_text="Overtime multiplier (e.g., 1.5 for 1.5x pay)",
                max_digits=5,
            ),
        ),
    ]
