# Generated by Django 5.2.1 on 2025-10-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_add_payslip_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarycomponent",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
