# Generated by Django 5.2.1 on 2025-11-01 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0006_alter_salarycomponent_abbreviation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollperiod",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes about this period"
            ),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the payroll was processed", null=True
            ),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who processed the payroll",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_periods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="processed_employees",
            field=models.IntegerField(
                default=0, help_text="Number of processed salary slips"
            ),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="total_deductions",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Sum of all deductions",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="total_employees",
            field=models.IntegerField(
                default=0, help_text="Total number of employees in this period"
            ),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="total_gross_pay",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Sum of all gross pay",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="total_net_pay",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Sum of all net pay",
                max_digits=15,
            ),
        ),
    ]
