# Generated by Django 5.2.1 on 2025-11-04 05:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0017_alter_employee_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Brief summary shown in lists (auto-generated if empty)",
                        max_length=300,
                        verbose_name="Summary",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Pinned announcements appear at the top",
                        verbose_name="Pinned",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All Employees"),
                            ("department", "Specific Department"),
                            ("role", "Specific Role"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Target Audience",
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Announcement will be visible from this date",
                        verbose_name="Publish Date",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Announcement will be hidden after this date",
                        null=True,
                        verbose_name="Expiry Date",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Optional file attachment (PDF, images, etc.)",
                        null=True,
                        upload_to="announcements/%Y/%m/",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "require_acknowledgment",
                    models.BooleanField(
                        default=False,
                        help_text="Employees must acknowledge they have read this",
                        verbose_name="Require Acknowledgment",
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="View Count"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "target_departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="announcements",
                        to="hr.department",
                        verbose_name="Target Departments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-is_pinned", "-publish_date"],
                "permissions": [
                    ("can_manage_announcements", "Can manage announcements")
                ],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Comment")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="announcements.announcement",
                        verbose_name="Announcement",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_comments",
                        to="hr.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement Comment",
                "verbose_name_plural": "Announcement Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Read At"),
                ),
                (
                    "acknowledged",
                    models.BooleanField(default=False, verbose_name="Acknowledged"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Acknowledged At"
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="announcements.announcement",
                        verbose_name="Announcement",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_reads",
                        to="hr.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement Read",
                "verbose_name_plural": "Announcement Reads",
                "ordering": ["-read_at"],
                "unique_together": {("announcement", "employee")},
            },
        ),
    ]
