# Generated by Django 5.2.1 on 2025-10-11 13:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityTypeMaster",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("activity_name", models.CharField(max_length=100, unique=True)),
                (
                    "activity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("planning", "Planning"),
                            ("execution", "Execution"),
                            ("testing", "Testing"),
                            ("documentation", "Documentation"),
                            ("meeting", "Meeting"),
                            ("communication", "Communication"),
                            ("research", "Research"),
                            ("review", "Review"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "billing_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "costing_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_billable", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "activity_types_master",
                "ordering": ["activity_name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("project_code", models.CharField(max_length=50, unique=True)),
                ("project_name", models.CharField(db_column="name", max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=300, null=True)),
                ("site_address", models.TextField(blank=True, null=True)),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "client_contact",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "client_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "expected_start_date",
                    models.DateField(blank=True, db_column="start_date", null=True),
                ),
                (
                    "expected_end_date",
                    models.DateField(blank=True, db_column="end_date", null=True),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, db_column="actual_completion_date", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("overdue", "Overdue"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "percent_complete",
                    models.IntegerField(
                        db_column="progress_percentage",
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        db_column="budget", decimal_places=2, default=0, max_digits=15
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("estimated_duration_days", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        blank=True,
                        db_column="project_manager_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "project_project",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "project_types",
                "ordering": ["type_name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectBudget",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("budget_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "budgeted_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "actual_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("fiscal_year", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_budgets",
            },
        ),
        migrations.CreateModel(
            name="ProjectInvoice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("invoice_id", models.UUIDField(blank=True, null=True)),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("invoice_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "timesheet_id",
                    models.BigIntegerField(
                        blank=True, db_column="timesheet_id", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_invoices",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("task_code", models.CharField(max_length=50, unique=True)),
                ("task_name", models.CharField(db_column="title", max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "expected_start_date",
                    models.DateField(blank=True, db_column="start_date", null=True),
                ),
                (
                    "expected_end_date",
                    models.DateField(blank=True, db_column="due_date", null=True),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, db_column="completion_date", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("working", "Working"),
                            ("pending_review", "Pending Review"),
                            ("overdue", "Overdue"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        db_column="progress_percentage",
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to="hr.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_projecttask",
                "ordering": ["expected_start_date", "task_name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("milestone_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("deliverable", "Deliverable"),
                            ("payment", "Payment"),
                            ("review", "Review"),
                            ("approval", "Approval"),
                            ("launch", "Launch"),
                            ("testing", "Testing"),
                            ("other", "Other"),
                        ],
                        default="deliverable",
                        max_length=20,
                    ),
                ),
                ("milestone_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Payment amount or budget allocation",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=False, help_text="Is this milestone billable to client?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "deliverables",
                    models.TextField(
                        blank=True,
                        help_text="List of deliverables for this milestone",
                        null=True,
                    ),
                ),
                (
                    "acceptance_criteria",
                    models.TextField(
                        blank=True,
                        help_text="Criteria for milestone completion",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_milestones",
                        to="hr.employee",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_milestones",
                        to="hr.employee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depends_on_milestones",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependent_milestones",
                        to="project.projectmilestone",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="project.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link milestone to a specific task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.projecttask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Milestone",
                "verbose_name_plural": "Project Milestones",
                "db_table": "project_milestones",
                "ordering": ["milestone_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectExpense",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("expense_code", models.CharField(max_length=50, unique=True)),
                ("expense_date", models.DateField()),
                (
                    "expense_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("is_billable", models.BooleanField(default=False)),
                ("is_reimbursable", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("attachment_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to="hr.employee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_expenses",
                        to="hr.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="project.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.projecttask",
                    ),
                ),
            ],
            options={
                "db_table": "project_expenses",
                "ordering": ["-expense_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("document_name", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("file_url", models.URLField()),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="project.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.projecttask",
                    ),
                ),
            ],
            options={
                "db_table": "project_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTimeTracking",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "total_estimated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total estimated hours for the project",
                        max_digits=10,
                        verbose_name="Total Estimated Hours",
                    ),
                ),
                (
                    "total_actual_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total hours logged across all timesheets",
                        max_digits=10,
                        verbose_name="Total Actual Hours",
                    ),
                ),
                (
                    "total_billable_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total billable hours across all timesheets",
                        max_digits=10,
                        verbose_name="Total Billable Hours",
                    ),
                ),
                (
                    "total_billed_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total hours that have been billed to client",
                        max_digits=10,
                        verbose_name="Total Billed Hours",
                    ),
                ),
                (
                    "total_billable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total billable amount across all timesheets",
                        max_digits=15,
                        verbose_name="Total Billable Amount",
                    ),
                ),
                (
                    "total_billed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount that has been billed to client",
                        max_digits=15,
                        verbose_name="Total Billed Amount",
                    ),
                ),
                (
                    "total_costing_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total internal costing amount",
                        max_digits=15,
                        verbose_name="Total Costing Amount",
                    ),
                ),
                (
                    "efficiency_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Billable hours / Total hours * 100",
                        max_digits=5,
                        verbose_name="Efficiency Rate (%)",
                    ),
                ),
                (
                    "utilization_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual hours / Estimated hours * 100",
                        max_digits=5,
                        verbose_name="Utilization Rate (%)",
                    ),
                ),
                (
                    "first_timesheet_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of first time entry",
                        null=True,
                        verbose_name="First Timesheet Date",
                    ),
                ),
                (
                    "last_timesheet_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of most recent time entry",
                        null=True,
                        verbose_name="Last Timesheet Date",
                    ),
                ),
                (
                    "last_calculated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When totals were last recalculated",
                        null=True,
                        verbose_name="Last Calculated At",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_tracking",
                        to="project.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Time Tracking",
                "verbose_name_plural": "Project Time Tracking",
                "db_table": "project_time_tracking",
            },
        ),
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("template_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("default_tasks", models.JSONField(blank=True, default=dict)),
                ("estimated_duration_days", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.projecttype",
                    ),
                ),
            ],
            options={
                "db_table": "project_templates",
                "ordering": ["template_name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectUpdate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField()),
                ("is_internal", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="project.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="project.projecttask",
                    ),
                ),
            ],
            options={
                "db_table": "project_updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=200)),
                ("team_code", models.CharField(blank=True, max_length=20, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "team_type",
                    models.CharField(
                        choices=[
                            ("development", "Development Team"),
                            ("design", "Design Team"),
                            ("qa", "Quality Assurance"),
                            ("devops", "DevOps Team"),
                            ("marketing", "Marketing Team"),
                            ("sales", "Sales Team"),
                            ("support", "Support Team"),
                            ("management", "Management Team"),
                            ("cross_functional", "Cross-Functional Team"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "max_members",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum number of team members"
                    ),
                ),
                (
                    "is_project_based",
                    models.BooleanField(
                        default=False, help_text="Team created for specific projects"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="company.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teams",
                        to="hr.department",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_teams",
                        to="hr.employee",
                    ),
                ),
                (
                    "team_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_teams",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "db_table": "project_teams",
                "ordering": ["team_name"],
            },
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timesheet_code", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_billable_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_billed_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_billable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_costing_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "per_hour_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("submitted_date", models.DateTimeField(blank=True, null=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_timesheets",
                        to="hr.employee",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_timesheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "timesheets",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TimesheetDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("activity_date", models.DateField()),
                ("from_time", models.TimeField(blank=True, null=True)),
                ("to_time", models.TimeField(blank=True, null=True)),
                ("hours", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_billable", models.BooleanField(default=True)),
                (
                    "billing_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "billing_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "costing_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "costing_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.activitytypemaster",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.projecttask",
                    ),
                ),
                (
                    "timesheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="project.timesheet",
                    ),
                ),
            ],
            options={
                "db_table": "timesheet_details",
                "ordering": ["activity_date", "from_time"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSettings",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to="project.project",
                    ),
                ),
                (
                    "use_custom_working_time",
                    models.BooleanField(
                        default=False,
                        help_text="Use project-specific working time instead of global schedule",
                    ),
                ),
                ("monday_start", models.TimeField(blank=True, null=True)),
                ("monday_end", models.TimeField(blank=True, null=True)),
                ("tuesday_start", models.TimeField(blank=True, null=True)),
                ("tuesday_end", models.TimeField(blank=True, null=True)),
                ("wednesday_start", models.TimeField(blank=True, null=True)),
                ("wednesday_end", models.TimeField(blank=True, null=True)),
                ("thursday_start", models.TimeField(blank=True, null=True)),
                ("thursday_end", models.TimeField(blank=True, null=True)),
                ("friday_start", models.TimeField(blank=True, null=True)),
                ("friday_end", models.TimeField(blank=True, null=True)),
                ("saturday_start", models.TimeField(blank=True, null=True)),
                ("saturday_end", models.TimeField(blank=True, null=True)),
                ("sunday_start", models.TimeField(blank=True, null=True)),
                ("sunday_end", models.TimeField(blank=True, null=True)),
                (
                    "break_duration",
                    models.IntegerField(
                        default=60,
                        help_text="Default lunch/break duration in minutes",
                        verbose_name="Break Duration (minutes)",
                    ),
                ),
                (
                    "break_start",
                    models.TimeField(
                        blank=True, help_text="Standard break start time", null=True
                    ),
                ),
                (
                    "flexible_hours",
                    models.BooleanField(
                        default=False, help_text="Allow flexible working hours"
                    ),
                ),
                (
                    "core_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Core hours start (for flexible schedule)",
                        null=True,
                    ),
                ),
                (
                    "core_hours_end",
                    models.TimeField(
                        blank=True,
                        help_text="Core hours end (for flexible schedule)",
                        null=True,
                    ),
                ),
                (
                    "required_hours_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Required working hours per day",
                        max_digits=4,
                    ),
                ),
                (
                    "working_days_per_week",
                    models.IntegerField(
                        default=6,
                        help_text="Number of working days per week (e.g., 5 or 6)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Working Days Per Week",
                    ),
                ),
                (
                    "use_custom_overtime_rules",
                    models.BooleanField(
                        default=False, help_text="Use project-specific overtime rules"
                    ),
                ),
                (
                    "overtime_rate_regular",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        help_text="Multiplier for regular overtime (e.g., 1.5 = 150%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Regular Overtime Rate",
                    ),
                ),
                (
                    "overtime_rate_weekend",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="Multiplier for weekend overtime",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Weekend Overtime Rate",
                    ),
                ),
                (
                    "overtime_rate_holiday",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.5,
                        help_text="Multiplier for holiday overtime",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Holiday Overtime Rate",
                    ),
                ),
                (
                    "min_overtime_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="Minimum minutes required to count as overtime",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Minimum Overtime Minutes",
                    ),
                ),
                (
                    "max_overtime_hours_per_day",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum overtime hours allowed per day (leave empty for no limit)",
                        max_digits=4,
                        null=True,
                        verbose_name="Max Overtime Hours Per Day",
                    ),
                ),
                (
                    "max_overtime_hours_per_week",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum overtime hours allowed per week (leave empty for no limit)",
                        max_digits=5,
                        null=True,
                        verbose_name="Max Overtime Hours Per Week",
                    ),
                ),
                (
                    "overtime_requires_approval",
                    models.BooleanField(
                        default=True, help_text="Overtime must be pre-approved"
                    ),
                ),
                (
                    "overtime_auto_approve_threshold",
                    models.IntegerField(
                        default=0,
                        help_text="Auto-approve overtime below this threshold (0 = always require approval)",
                        verbose_name="Auto-approve Threshold (minutes)",
                    ),
                ),
                (
                    "use_custom_attendance_rules",
                    models.BooleanField(
                        default=False, help_text="Use project-specific attendance rules"
                    ),
                ),
                (
                    "late_grace_period",
                    models.IntegerField(
                        default=15,
                        help_text="Grace period before marking as late",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="Late Grace Period (minutes)",
                    ),
                ),
                (
                    "early_leave_grace_period",
                    models.IntegerField(
                        default=15,
                        help_text="Grace period before marking as early leave",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="Early Leave Grace Period (minutes)",
                    ),
                ),
                (
                    "require_biometric_checkin",
                    models.BooleanField(
                        default=False, help_text="Require biometric device for check-in"
                    ),
                ),
                (
                    "allow_remote_attendance",
                    models.BooleanField(
                        default=True, help_text="Allow remote/work-from-home attendance"
                    ),
                ),
                (
                    "require_location_tracking",
                    models.BooleanField(
                        default=False, help_text="Require GPS location for attendance"
                    ),
                ),
                (
                    "late_deduction_per_minute",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount deducted per minute of lateness",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Late Deduction Per Minute",
                    ),
                ),
                (
                    "absence_deduction_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount deducted for unexcused absence",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Absence Deduction Per Day",
                    ),
                ),
                (
                    "max_late_minutes_per_month",
                    models.IntegerField(
                        default=120,
                        help_text="Maximum allowed late minutes per month",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Max Late Minutes Per Month",
                    ),
                ),
                (
                    "max_absences_per_month",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum allowed absences per month",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Max Absences Per Month",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_project_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Settings",
                "verbose_name_plural": "Project Settings",
                "db_table": "project_settings",
            },
        ),
        migrations.CreateModel(
            name="ProjectTeamMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "pay_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Normal", "Normal"),
                            ("PH", "Public Holiday"),
                            ("OT", "Overtime"),
                            ("Weekend", "Weekend"),
                        ],
                        default="Normal",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "daily_rate_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Daily rate in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=1.0,
                        help_text="Pay multiplier (e.g., 1.0, 1.5, 2.0)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        db_column="daily_rate",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "ot_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overtime rate per day",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, db_column="assigned_date", null=True),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="worker_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to="hr.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_projectteam",
                "unique_together": {("project", "employee")},
            },
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("lag_days", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "depends_on_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_tasks",
                        to="project.projecttask",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="project.projecttask",
                    ),
                ),
            ],
            options={
                "db_table": "task_dependencies",
                "unique_together": {("task", "depends_on_task")},
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("team_lead", "Team Lead"),
                            ("senior_developer", "Senior Developer"),
                            ("developer", "Developer"),
                            ("junior_developer", "Junior Developer"),
                            ("designer", "Designer"),
                            ("qa_engineer", "QA Engineer"),
                            ("devops_engineer", "DevOps Engineer"),
                            ("business_analyst", "Business Analyst"),
                            ("project_manager", "Project Manager"),
                            ("product_owner", "Product Owner"),
                            ("scrum_master", "Scrum Master"),
                            ("consultant", "Consultant"),
                            ("intern", "Intern"),
                            ("other", "Other"),
                        ],
                        default="developer",
                        max_length=50,
                    ),
                ),
                (
                    "custom_role",
                    models.CharField(
                        blank=True,
                        help_text="Custom role name if 'other' is selected",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True,
                        help_text="Specific responsibilities in this team",
                        null=True,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contractor", "Contractor"),
                            ("consultant", "Consultant"),
                            ("temporary", "Temporary"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "allocation_percentage",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Percentage of time allocated to this team",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hourly rate for this team role",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for permanent membership",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "can_manage_team",
                    models.BooleanField(
                        default=False, help_text="Can add/remove team members"
                    ),
                ),
                (
                    "can_assign_tasks",
                    models.BooleanField(
                        default=False, help_text="Can assign tasks to team members"
                    ),
                ),
                (
                    "can_view_reports",
                    models.BooleanField(
                        default=False, help_text="Can view team performance reports"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_team_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="hr.employee",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="project.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "db_table": "team_members",
                "ordering": ["-created_at"],
                "unique_together": {("team", "employee")},
            },
        ),
    ]
