# Generated by Django 5.2.1 on 2025-11-01 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the branch", max_length=200),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique branch code", max_length=50, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the branch", null=True
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Branch address", null=True),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City where the branch is located",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "state_province",
                    models.CharField(
                        blank=True,
                        help_text="State or province",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal or ZIP code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Cambodia",
                        help_text="Country where the branch is located",
                        max_length=100,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number",
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in Cambodia format: +855xxxxxxxx or 0xxxxxxxx (8-10 digits after prefix)",
                                regex="^(\\+?855|0)\\d{8,10}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Branch contact email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True,
                        help_text="Branch manager name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this branch is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "ordering": ["name"],
            },
        ),
    ]
