# Generated by Django 5.2.1 on 2025-10-11 13:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("zone", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardReplacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("lost", "Lost"),
                            ("damaged", "Damaged"),
                            ("expired", "Expired"),
                            ("stolen", "Stolen"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Card Replacement",
                "verbose_name_plural": "Card Replacements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeCardPrintingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("print_date", models.DateTimeField(auto_now_add=True)),
                (
                    "print_number",
                    models.PositiveIntegerField(
                        help_text="Sequential print number for this card"
                    ),
                ),
                (
                    "charge_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Employee Card Printing History",
                "verbose_name_plural": "Employee Card Printing History",
                "ordering": ["-print_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeIDCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("printed", "Printed"),
                            ("delivered", "Delivered"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("lost", "Lost"),
                            ("damaged", "Damaged"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("manager", "Manager"),
                            ("executive", "Executive"),
                            ("temporary", "Temporary"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("request_date", models.DateTimeField(blank=True, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="employee_id_photos/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "print_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this card has been printed",
                    ),
                ),
                (
                    "first_print_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of first print (free)", null=True
                    ),
                ),
                (
                    "last_print_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of most recent print", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Employee ID Card",
                "verbose_name_plural": "Employee ID Cards",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="PrintBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique batch identifier",
                        unique=True,
                    ),
                ),
                (
                    "batch_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name for the batch",
                        max_length=100,
                    ),
                ),
                ("print_date", models.DateTimeField(auto_now_add=True)),
                (
                    "card_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of cards in this batch"
                    ),
                ),
                (
                    "batch_type",
                    models.CharField(
                        choices=[
                            ("worker", "Worker ID Cards"),
                            ("employee", "Employee ID Cards"),
                            ("mixed", "Mixed Card Types"),
                        ],
                        default="worker",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about this print batch"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Print Batch",
                "verbose_name_plural": "Print Batches",
                "ordering": ["-print_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkerIDCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("printed", "Printed"),
                            ("delivered", "Delivered"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="worker_id_photos/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "print_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this card has been printed",
                    ),
                ),
                (
                    "first_print_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of first print (free)", null=True
                    ),
                ),
                (
                    "last_print_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of most recent print", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Worker ID Card",
                "verbose_name_plural": "Worker ID Cards",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="CardPrintingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("print_date", models.DateTimeField(auto_now_add=True)),
                (
                    "print_number",
                    models.PositiveIntegerField(
                        help_text="Sequential print number for this card"
                    ),
                ),
                (
                    "charge_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "printed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="printed_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Printing History",
                "verbose_name_plural": "Card Printing History",
                "ordering": ["-print_date"],
            },
        ),
        migrations.CreateModel(
            name="CardCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("reprint", "Card Reprint"),
                            ("lost", "Lost Card Replacement"),
                            ("damaged", "Damaged Card Replacement"),
                            ("other", "Other"),
                        ],
                        default="reprint",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "auto_invoice",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create invoice for this charge",
                    ),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_charges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_charges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated invoice for this charge",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_charges",
                        to="billing.invoice",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_charges",
                        to="zone.worker",
                    ),
                ),
                (
                    "print_history",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge_record",
                        to="cards.cardprintinghistory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Charge",
                "verbose_name_plural": "Card Charges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeCardCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("reprint", "Card Reprint"),
                            ("lost", "Lost Card Replacement"),
                            ("damaged", "Damaged Card Replacement"),
                            ("other", "Other"),
                        ],
                        default="reprint",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "auto_invoice",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create invoice for this charge",
                    ),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_employee_charges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_employee_charges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Card Charge",
                "verbose_name_plural": "Employee Card Charges",
                "ordering": ["-created_at"],
            },
        ),
    ]
