# Generated by Django 5.2.1 on 2025-10-11 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("cards", "0001_initial"),
        ("hr", "0001_initial"),
        ("zone", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecardcharge",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_charges",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeecardcharge",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated invoice for this charge",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_card_charges",
                to="billing.invoice",
            ),
        ),
        migrations.AddField(
            model_name="employeecardprintinghistory",
            name="printed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="printed_employee_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeecardcharge",
            name="print_history",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charge_record",
                to="cards.employeecardprintinghistory",
            ),
        ),
        migrations.AddField(
            model_name="employeeidcard",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_id_cards",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeecardprintinghistory",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="printing_history",
                to="cards.employeeidcard",
            ),
        ),
        migrations.AddField(
            model_name="employeecardcharge",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charges",
                to="cards.employeeidcard",
            ),
        ),
        migrations.AddField(
            model_name="cardreplacement",
            name="employee_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replacements",
                to="cards.employeeidcard",
            ),
        ),
        migrations.AddField(
            model_name="printbatch",
            name="printed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="print_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeecardprintinghistory",
            name="print_batch",
            field=models.ForeignKey(
                blank=True,
                help_text="Batch this print belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_printing_records",
                to="cards.printbatch",
            ),
        ),
        migrations.AddField(
            model_name="cardprintinghistory",
            name="print_batch",
            field=models.ForeignKey(
                blank=True,
                help_text="Batch this print belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worker_printing_records",
                to="cards.printbatch",
            ),
        ),
        migrations.AddField(
            model_name="workeridcard",
            name="worker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_cards",
                to="zone.worker",
            ),
        ),
        migrations.AddField(
            model_name="cardreplacement",
            name="worker_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replacements",
                to="cards.workeridcard",
            ),
        ),
        migrations.AddField(
            model_name="cardprintinghistory",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="printing_history",
                to="cards.workeridcard",
            ),
        ),
        migrations.AddField(
            model_name="cardcharge",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charges",
                to="cards.workeridcard",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeecardprintinghistory",
            unique_together={("card", "print_number")},
        ),
        migrations.AlterUniqueTogether(
            name="cardprintinghistory",
            unique_together={("card", "print_number")},
        ),
    ]
