# Generated by Django 5.2.1 on 2025-10-11 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("zone", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_batch_request",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a batch request for multiple workers",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("employment", "Employment Certificate"),
                            ("salary", "Salary Certificate"),
                            ("experience", "Experience Certificate"),
                            ("conduct", "Good Conduct Certificate"),
                            ("service", "Service Certificate"),
                            ("reference", "Reference Letter"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("bank_loan", "Bank Loan Application"),
                            ("visa_application", "Application for visa extension"),
                            ("new_employment", "New Employment"),
                            ("housing_rental", "Housing Rental"),
                            ("government_requirement", "Government Requirement"),
                            ("personal_use", "Personal Use"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("normal", "Normal (5-7 days)"),
                            ("urgent", "Urgent (2-3 days)"),
                            ("emergency", "Emergency (Same day)"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "specific_details",
                    models.TextField(
                        blank=True,
                        help_text="Additional details or specific requirements",
                    ),
                ),
                (
                    "include_salary",
                    models.BooleanField(
                        default=False,
                        help_text="Include salary information in certificate",
                    ),
                ),
                (
                    "include_start_date",
                    models.BooleanField(
                        default=True, help_text="Include employment start date"
                    ),
                ),
                (
                    "include_position",
                    models.BooleanField(
                        default=True, help_text="Include current position"
                    ),
                ),
                (
                    "include_department",
                    models.BooleanField(
                        default=True, help_text="Include department information"
                    ),
                ),
                (
                    "custom_text",
                    models.TextField(
                        blank=True, help_text="Custom text to include in certificate"
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup from Office"),
                            ("mail", "Mail to Address"),
                            ("email", "Email Copy"),
                            ("courier", "Courier Service"),
                        ],
                        default="pickup",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(
                        blank=True,
                        help_text="Required if delivery method is mail or courier",
                    ),
                ),
                (
                    "delivery_contact",
                    models.CharField(
                        blank=True,
                        help_text="Contact person for delivery",
                        max_length=100,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "certificate_generated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificate_requests/certificates/",
                    ),
                ),
                ("expected_completion", models.DateField(blank=True, null=True)),
                ("actual_completion", models.DateField(blank=True, null=True)),
                (
                    "request_ref",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workers",
                    models.ManyToManyField(
                        related_name="certificate_requests", to="zone.worker"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificateRequestWorkerService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the service"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certificate_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_services",
                        to="eform.certificaterequest",
                    ),
                ),
                (
                    "visa_service_charge",
                    models.ForeignKey(
                        blank=True,
                        help_text="Visa service charge for this worker",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificate_worker_services",
                        to="billing.service",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zone.worker"
                    ),
                ),
            ],
            options={
                "ordering": ["worker__first_name", "worker__last_name"],
            },
        ),
        migrations.CreateModel(
            name="ExtensionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("passport_number", models.CharField(max_length=50)),
                ("passport_expiry_date", models.DateField(blank=True, null=True)),
                ("passport_issued_date", models.DateField(blank=True, null=True)),
                (
                    "current_visa_type",
                    models.CharField(
                        choices=[
                            ("tourist", "Tourist Visa"),
                            ("business", "Business Visa"),
                            ("work", "Work Visa"),
                            ("student", "Student Visa"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_visa_number", models.CharField(blank=True, max_length=50)),
                ("current_visa_expiry", models.DateField()),
                ("entry_date", models.DateField()),
                ("work_permit_number", models.CharField(blank=True, max_length=50)),
                ("work_permit_expiry", models.DateField(blank=True, null=True)),
                (
                    "address_name",
                    models.CharField(
                        blank=True, help_text="Address name in Cambodia", max_length=200
                    ),
                ),
                (
                    "house_no",
                    models.CharField(
                        blank=True, help_text="House Number", max_length=50
                    ),
                ),
                (
                    "street_no",
                    models.CharField(
                        blank=True, help_text="Street Number", max_length=50
                    ),
                ),
                (
                    "commune",
                    models.CharField(
                        blank=True, help_text="Commune/Sangkat", max_length=100
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, help_text="District/Khan", max_length=100
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        default="KOH KONG RESORT",
                        help_text="Institution/Organization Name",
                        max_length=200,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, help_text="Position/Job Title", max_length=100
                    ),
                ),
                (
                    "extension_type",
                    models.CharField(
                        choices=[
                            ("tourist", "Tourist Extension"),
                            ("business", "Business Extension"),
                            ("work", "Work Permit Extension"),
                            ("emergency", "Emergency Extension"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "extension_duration",
                    models.PositiveIntegerField(help_text="Duration in days"),
                ),
                (
                    "extension_reason",
                    models.CharField(
                        choices=[
                            ("employment", "Employment purposes"),
                            ("medical", "Medical treatment"),
                            ("family", "Family matters"),
                            ("business", "Business activities"),
                            ("tourism", "Tourism"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("extension_start_date", models.DateField()),
                ("additional_details", models.TextField(blank=True)),
                (
                    "passport_copy",
                    models.FileField(
                        blank=True, null=True, upload_to="extension_requests/passports/"
                    ),
                ),
                (
                    "visa_copy",
                    models.FileField(
                        blank=True, null=True, upload_to="extension_requests/visas/"
                    ),
                ),
                (
                    "employment_letter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="extension_requests/employment/",
                    ),
                ),
                (
                    "other_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="extension_requests/other/"
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated billing service",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.service",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_requests",
                        to="zone.worker",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("allow_multiple_submissions", models.BooleanField(default=True)),
                ("collect_email", models.BooleanField(default=False)),
                ("require_login", models.BooleanField(default=False)),
                ("submission_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("textarea", "Textarea"),
                            ("email", "Email"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("time", "Time"),
                            ("datetime", "Date and Time"),
                            ("select", "Select Dropdown"),
                            ("radio", "Radio Button"),
                            ("checkbox", "Checkbox"),
                            ("file", "File Upload"),
                            ("url", "URL"),
                            ("tel", "Phone"),
                            ("range", "Range Slider"),
                            ("color", "Color Picker"),
                        ],
                        max_length=20,
                    ),
                ),
                ("help_text", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("options", models.JSONField(blank=True, default=list)),
                ("min_length", models.PositiveIntegerField(blank=True, null=True)),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                (
                    "pattern",
                    models.CharField(
                        blank=True,
                        help_text="Regex pattern for validation",
                        max_length=500,
                    ),
                ),
                ("default_value", models.TextField(blank=True)),
                ("css_class", models.CharField(blank=True, max_length=200)),
                ("placeholder", models.CharField(blank=True, max_length=200)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="eform.form",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="eform.form",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("template_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="certificaterequest",
            index=models.Index(
                fields=["request_number"], name="eform_certi_request_68fa62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificaterequest",
            index=models.Index(fields=["status"], name="eform_certi_status_8db4a5_idx"),
        ),
        migrations.AddIndex(
            model_name="certificaterequest",
            index=models.Index(
                fields=["created_at"], name="eform_certi_created_a9c53f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificaterequest",
            index=models.Index(
                fields=["certificate_type"], name="eform_certi_certifi_91ad24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificaterequest",
            index=models.Index(
                fields=["is_batch_request"], name="eform_certi_is_batc_94680e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="certificaterequestworkerservice",
            unique_together={("certificate_request", "worker")},
        ),
        migrations.AddIndex(
            model_name="extensionrequest",
            index=models.Index(
                fields=["request_number"], name="eform_exten_request_a10689_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extensionrequest",
            index=models.Index(fields=["status"], name="eform_exten_status_52e865_idx"),
        ),
        migrations.AddIndex(
            model_name="extensionrequest",
            index=models.Index(
                fields=["worker"], name="eform_exten_worker__8b9dd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extensionrequest",
            index=models.Index(
                fields=["created_at"], name="eform_exten_created_57b093_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="formsubmission",
            unique_together={("form", "submitted_by")},
        ),
    ]
