# Generated by Django 5.2.1 on 2025-10-11 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correction_type",
                    models.CharField(
                        choices=[
                            ("clock_in", "Clock In Time"),
                            ("clock_out", "Clock Out Time"),
                            ("both", "Both Clock In and Out"),
                            ("status", "Attendance Status"),
                        ],
                        max_length=50,
                        verbose_name="Correction Type",
                    ),
                ),
                (
                    "new_clock_in",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="New Clock In"
                    ),
                ),
                (
                    "new_clock_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="New Clock Out"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("early_leave", "Early Leave"),
                            ("half_day", "Half Day"),
                            ("holiday", "Holiday"),
                            ("weekend", "Weekend"),
                            ("leave", "On Leave"),
                        ],
                        max_length=20,
                        verbose_name="New Status",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Reason for Correction")),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="attendance/corrections/",
                        verbose_name="Supporting Document",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Attendance Correction",
                "verbose_name_plural": "Attendance Corrections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Policy Name")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Policy Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "late_deduction_per_minute",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Late Deduction Per Minute",
                    ),
                ),
                (
                    "max_late_minutes_per_month",
                    models.IntegerField(
                        default=120, verbose_name="Max Late Minutes Per Month"
                    ),
                ),
                (
                    "late_penalty_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Late Penalty Amount",
                    ),
                ),
                (
                    "absence_deduction_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Absence Deduction Per Day",
                    ),
                ),
                (
                    "max_absences_per_month",
                    models.IntegerField(
                        default=3, verbose_name="Max Absences Per Month"
                    ),
                ),
                (
                    "overtime_rate_regular",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=3,
                        verbose_name="Regular Overtime Rate",
                    ),
                ),
                (
                    "overtime_rate_holiday",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        max_digits=3,
                        verbose_name="Holiday Overtime Rate",
                    ),
                ),
                (
                    "min_overtime_minutes",
                    models.IntegerField(
                        default=30, verbose_name="Minimum Overtime Minutes"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Attendance Policy",
                "verbose_name_plural": "Attendance Policies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "clock_in",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Clock In"
                    ),
                ),
                (
                    "clock_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Clock Out"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location or project site",
                        max_length=200,
                        verbose_name="Work Location",
                    ),
                ),
                (
                    "is_remote_work",
                    models.BooleanField(
                        default=False,
                        help_text="Employee working remotely today",
                        verbose_name="Remote Work",
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Total Hours",
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Overtime Hours",
                    ),
                ),
                (
                    "late_minutes",
                    models.IntegerField(default=0, verbose_name="Late Minutes"),
                ),
                (
                    "early_leave_minutes",
                    models.IntegerField(default=0, verbose_name="Early Leave Minutes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("early_leave", "Early Leave"),
                            ("half_day", "Half Day"),
                            ("holiday", "Holiday"),
                            ("weekend", "Weekend"),
                            ("leave", "On Leave"),
                        ],
                        default="absent",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_manual_entry",
                    models.BooleanField(default=False, verbose_name="Manual Entry"),
                ),
                (
                    "manual_entry_reason",
                    models.TextField(blank=True, verbose_name="Manual Entry Reason"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "ordering": ["-date", "employee"],
            },
        ),
        migrations.CreateModel(
            name="BiometricDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Device ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Device Name")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("fingerprint", "Fingerprint Scanner"),
                            ("face", "Face Recognition"),
                            ("iris", "Iris Scanner"),
                            ("card", "Card Reader"),
                            ("multi", "Multi-Modal"),
                        ],
                        default="fingerprint",
                        max_length=20,
                        verbose_name="Device Type",
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="Location")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("port", models.IntegerField(default=4370, verbose_name="Port")),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Serial Number"
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Firmware Version"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Under Maintenance"),
                            ("offline", "Offline"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Sync"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Biometric Device",
                "verbose_name_plural": "Biometric Devices",
                "ordering": ["location", "name"],
            },
        ),
        migrations.CreateModel(
            name="BiometricTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("fingerprint", "Fingerprint"),
                            ("face", "Face"),
                            ("iris", "Iris"),
                            ("card", "Card"),
                        ],
                        max_length=20,
                        verbose_name="Template Type",
                    ),
                ),
                ("template_data", models.TextField(verbose_name="Template Data")),
                (
                    "finger_index",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Finger Index",
                    ),
                ),
                (
                    "quality_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Quality Score",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is Primary"),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enrolled At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Biometric Template",
                "verbose_name_plural": "Biometric Templates",
            },
        ),
        migrations.CreateModel(
            name="BreakRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "break_type",
                    models.CharField(
                        choices=[
                            ("lunch", "Lunch Break"),
                            ("tea", "Tea Break"),
                            ("personal", "Personal Break"),
                            ("prayer", "Prayer Break"),
                            ("other", "Other"),
                        ],
                        default="lunch",
                        max_length=20,
                        verbose_name="Break Type",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Start Time")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Time"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=0, verbose_name="Duration (minutes)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Break Record",
                "verbose_name_plural": "Break Records",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="Effective From")),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective To"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Employee Schedule",
                "verbose_name_plural": "Employee Schedules",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="OvertimeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Hours"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                (
                    "overtime_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=5,
                        verbose_name="Overtime Rate",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Overtime Request",
                "verbose_name_plural": "Overtime Requests",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Planned hours to work on this project",
                        max_digits=4,
                        verbose_name="Allocated Hours",
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual hours worked on this project (from timecard)",
                        max_digits=4,
                        verbose_name="Actual Hours",
                    ),
                ),
                (
                    "work_location",
                    models.CharField(
                        blank=True,
                        help_text="Specific location for this project work",
                        max_length=200,
                        verbose_name="Work Location",
                    ),
                ),
                (
                    "is_primary_project",
                    models.BooleanField(
                        default=False,
                        help_text="Main project for this attendance day",
                        verbose_name="Primary Project",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Project Work Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project Attendance",
                "verbose_name_plural": "Project Attendance",
                "ordering": ["-attendance__date", "project__project_name"],
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Schedule Name"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Schedule Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "monday_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Monday Start"
                    ),
                ),
                (
                    "monday_end",
                    models.TimeField(blank=True, null=True, verbose_name="Monday End"),
                ),
                (
                    "tuesday_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Tuesday Start"
                    ),
                ),
                (
                    "tuesday_end",
                    models.TimeField(blank=True, null=True, verbose_name="Tuesday End"),
                ),
                (
                    "wednesday_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Wednesday Start"
                    ),
                ),
                (
                    "wednesday_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Wednesday End"
                    ),
                ),
                (
                    "thursday_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Thursday Start"
                    ),
                ),
                (
                    "thursday_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Thursday End"
                    ),
                ),
                (
                    "friday_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Friday Start"
                    ),
                ),
                (
                    "friday_end",
                    models.TimeField(blank=True, null=True, verbose_name="Friday End"),
                ),
                (
                    "saturday_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Saturday Start"
                    ),
                ),
                (
                    "saturday_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Saturday End"
                    ),
                ),
                (
                    "sunday_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Sunday Start"
                    ),
                ),
                (
                    "sunday_end",
                    models.TimeField(blank=True, null=True, verbose_name="Sunday End"),
                ),
                (
                    "break_duration",
                    models.IntegerField(
                        default=60, verbose_name="Break Duration (minutes)"
                    ),
                ),
                (
                    "break_start",
                    models.TimeField(blank=True, null=True, verbose_name="Break Start"),
                ),
                (
                    "flexible_hours",
                    models.BooleanField(default=False, verbose_name="Flexible Hours"),
                ),
                (
                    "core_hours_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Core Hours Start"
                    ),
                ),
                (
                    "core_hours_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Core Hours End"
                    ),
                ),
                (
                    "required_hours_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        max_digits=4,
                        verbose_name="Required Hours Per Day",
                    ),
                ),
                (
                    "late_grace_period",
                    models.IntegerField(
                        default=15, verbose_name="Late Grace Period (minutes)"
                    ),
                ),
                (
                    "early_leave_grace_period",
                    models.IntegerField(
                        default=15, verbose_name="Early Leave Grace Period (minutes)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Work Schedule",
                "verbose_name_plural": "Work Schedules",
                "ordering": ["name"],
            },
        ),
    ]
