# Generated by Django 5.2.1 on 2025-11-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_overtimerequest_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={
                "ordering": ["-date", "-clock_in", "employee"],
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
            },
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="clock_in_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS latitude for clock in location",
                max_digits=9,
                null=True,
                verbose_name="Clock In Latitude",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="clock_in_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS longitude for clock in location",
                max_digits=9,
                null=True,
                verbose_name="Clock In Longitude",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="clock_out_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS latitude for clock out location",
                max_digits=9,
                null=True,
                verbose_name="Clock Out Latitude",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="clock_out_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS longitude for clock out location",
                max_digits=9,
                null=True,
                verbose_name="Clock Out Longitude",
            ),
        ),
    ]
